CREATE TABLE IF NOT EXISTS magic_items (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  rarity TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_published BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT magic_items_rarity_check CHECK (
    rarity IN ('common', 'uncommon', 'rare', 'veryrare', 'legendary')
  ),
  CONSTRAINT magic_items_name_rarity_unique UNIQUE (name, rarity)
);

CREATE INDEX IF NOT EXISTS magic_items_rarity_sort_order_idx
  ON magic_items (rarity, sort_order, id);

INSERT INTO magic_items (
  name,
  rarity,
  sort_order,
  is_published
)
VALUES
  ('Armblade', 'common', 10, true),
  ('Armor of Gleaming', 'common', 20, true),
  ('Aurora Dust', 'common', 30, true),
  ('Bag of Bellstones', 'common', 40, true),
  ('Ball of Wild Earth', 'common', 50, true),
  ('Band of Loyalty', 'common', 60, true),
  ('Bead of Nourishment', 'common', 70, true),
  ('Bead of Refreshment', 'common', 80, true),
  ('Bell of Alarm', 'common', 90, true),
  ('Bird''s-Eye Bolt', 'common', 100, true),
  ('Bloody Marilith (Common)', 'common', 110, true),
  ('Bonfire Charm', 'common', 120, true),
  ('Book of Instant Copying', 'common', 130, true),
  ('Boots of False Tracks', 'common', 140, true),
  ('Bottle of Boundless Coffee', 'common', 150, true),
  ('Breathing Bubble', 'common', 160, true),
  ('Bullfrog Totem', 'common', 170, true),
  ('Camper''s Crutch', 'common', 180, true),
  ('Candle of the Deep', 'common', 190, true),
  ('Candleflame Helm', 'common', 200, true),
  ('Candy Xorn', 'common', 210, true),
  ('Cartographer''s Map Case', 'common', 220, true),
  ('Cast-Off Armor', 'common', 230, true),
  ('Celestial Sunrise (Common)', 'common', 240, true),
  ('Charlatan''s Die', 'common', 250, true),
  ('Chest of Preserving', 'common', 260, true),
  ('Cleaning Cube', 'common', 270, true),
  ('Cleansing Stone', 'common', 280, true),
  ('Cloak of Billowing', 'common', 290, true),
  ('Cloak of Many Fashions', 'common', 300, true),
  ('Clockwork Amulet', 'common', 310, true),
  ('Clothes of Mending', 'common', 320, true),
  ('Coin of Decisionry (Rank 2)', 'common', 330, true),
  ('Coin of Delving', 'common', 340, true),
  ('Corvid Bangle', 'common', 350, true),
  ('Cuddly Strixhaven Mascot', 'common', 360, true),
  ('Dark Shard Amulet', 'common', 370, true),
  ('Djinn and Tonic (Common)', 'common', 380, true),
  ('Documancy Satchel (Rank 2)', 'common', 390, true),
  ('Doublet of Dramatic Demise', 'common', 400, true),
  ('Dread Helm', 'common', 410, true),
  ('Dress of Many Pockets', 'common', 420, true),
  ('Drowner''s Pearl', 'common', 430, true),
  ('Ear Horn of Hearing', 'common', 440, true),
  ('Earring of Message', 'common', 450, true),
  ('Enduring Spellbook', 'common', 460, true),
  ('Ersatz Eye', 'common', 470, true),
  ('Everbright Lantern', 'common', 480, true),
  ('Feather Fall Token', 'common', 490, true),
  ('Forecaster''s Cloak', 'common', 500, true),
  ('Fortune''s Flower', 'common', 510, true),
  ('Foxfire Charm', 'common', 520, true),
  ('Freerunner''s Armor', 'common', 530, true),
  ('Glamerweave', 'common', 540, true),
  ('Griffon Coinpouch', 'common', 550, true),
  ('Griffon Key Loop', 'common', 560, true),
  ('Hat of Osnomnosis', 'common', 570, true),
  ('Hat of Vermin', 'common', 580, true),
  ('Hat of Wizardry', 'common', 590, true),
  ('Headband of the Sweatless', 'common', 600, true),
  ('Hedgewitch''s Gardening Cane', 'common', 610, true),
  ('Heward’s Handy Spice Pouch', 'common', 620, true),
  ('Horn of Silent Alarm', 'common', 630, true),
  ('Illuminator''s Tattoo', 'common', 640, true),
  ('Imbued Wood Focus', 'common', 650, true),
  ('Inker''s Armband', 'common', 660, true),
  ('Inspector''s Silverware', 'common', 670, true),
  ('Instrument of Illusions', 'common', 680, true),
  ('Instrument of Scribing', 'common', 690, true),
  ('Keycharm', 'common', 700, true),
  ('Lantern of Tracking', 'common', 710, true),
  ('Leatherbeard', 'common', 720, true),
  ('Light Sling', 'common', 730, true),
  ('Lock of Trickery', 'common', 740, true),
  ('Magnificent Pocket Vanity', 'common', 750, true),
  ('Masks of the Sacred Beasts (Crocodile)', 'common', 760, true),
  ('Masque Charm', 'common', 770, true),
  ('Masquerade Tattoo', 'common', 780, true),
  ('Medal of Muscle', 'common', 790, true),
  ('Medal of the Conch', 'common', 800, true),
  ('Medal of the Horizonback', 'common', 810, true),
  ('Medal of the Maze', 'common', 820, true),
  ('Medal of the Meat Pie', 'common', 830, true),
  ('Medal of the Wetlands', 'common', 840, true),
  ('Medal of Wit', 'common', 850, true),
  ('Moodmark Paint', 'common', 860, true),
  ('Moon-Touched Sword', 'common', 870, true),
  ('Mystery Key', 'common', 880, true),
  ('Oaken Candle', 'common', 890, true),
  ('Orb of Direction', 'common', 900, true),
  ('Orb of Gonging', 'common', 910, true),
  ('Orb of Remembrance', 'common', 920, true),
  ('Orb of Shielding', 'common', 930, true),
  ('Orb of Time', 'common', 940, true),
  ('Orostead Iced Tea (Common)', 'common', 950, true),
  ('Performer''s Puppet', 'common', 960, true),
  ('Perfume of Bewitching', 'common', 970, true),
  ('Periscope Rod', 'common', 980, true),
  ('Pipe of Remembrance', 'common', 990, true),
  ('Pipe of Smoke Monsters', 'common', 1000, true),
  ('Pole of Angling', 'common', 1010, true),
  ('Pole of Collapsing', 'common', 1020, true),
  ('Poltergeist Candle Holder', 'common', 1030, true),
  ('Pot of Awakening', 'common', 1040, true),
  ('Potion of Climbing', 'common', 1050, true),
  ('Pressure Capsule', 'common', 1060, true),
  ('Prism Glasses', 'common', 1070, true),
  ('Prosthetic Armblade', 'common', 1080, true),
  ('Prosthetic Limb', 'common', 1090, true),
  ('Redsmith Crucible Set', 'common', 1100, true),
  ('Redsmith Hammer', 'common', 1110, true),
  ('Rod of Endless Light', 'common', 1120, true),
  ('Rope Caster', 'common', 1130, true),
  ('Rope of Mending', 'common', 1140, true),
  ('Rose Quartz Koi', 'common', 1150, true),
  ('Ruby of the War Mage', 'common', 1160, true),
  ('Scribe''s Pen', 'common', 1170, true),
  ('Sekolahian Worshiping Statuette', 'common', 1180, true),
  ('Shield of Expression', 'common', 1190, true),
  ('Shifter''s Shine (Common)', 'common', 1200, true),
  ('Shiftweave', 'common', 1210, true),
  ('Shimmering Spectacles', 'common', 1220, true),
  ('Shipwright''s Watch', 'common', 1230, true),
  ('Silver Coin of Duvra', 'common', 1240, true),
  ('Silver Star Cane', 'common', 1250, true),
  ('Sleepytime Sheep Stuffy', 'common', 1260, true),
  ('Smoldering Armor', 'common', 1270, true),
  ('Snow Rider''s Sleigh', 'common', 1280, true),
  ('Spell Scroll (1st Level)', 'common', 1290, true),
  ('Spell Scroll (Cantrip)', 'common', 1300, true),
  ('Spellshard', 'common', 1310, true),
  ('Staff of Adornment', 'common', 1320, true),
  ('Staff of Bird Calls', 'common', 1330, true),
  ('Staff of Flowers', 'common', 1340, true),
  ('Stalwart Staff', 'common', 1350, true),
  ('Status Signets', 'common', 1360, true),
  ('Storm Seer Lamp', 'common', 1370, true),
  ('Storyteller''s Stein', 'common', 1380, true),
  ('Strixhaven Pennant', 'common', 1390, true),
  ('Stylist''s Circlet', 'common', 1400, true),
  ('Talking Doll', 'common', 1410, true),
  ('Tattoo, Spellwrought (1st Level)', 'common', 1420, true),
  ('Tattoo, Spellwrought (Cantrip)', 'common', 1430, true),
  ('Tea Weird', 'common', 1440, true),
  ('Thermal Cube', 'common', 1450, true),
  ('Tide Turner', 'common', 1460, true),
  ('Turtle Brooch', 'common', 1470, true),
  ('Veteran''s Cane', 'common', 1480, true),
  ('Vox Seeker', 'common', 1490, true),
  ('Walloping Ammunition', 'common', 1500, true),
  ('Wand of Conducting', 'common', 1510, true),
  ('Wand of Pyrotechnics', 'common', 1520, true),
  ('Wand of Scowls', 'common', 1530, true),
  ('Wand of Smiles', 'common', 1540, true),
  ('Wand Sheath', 'common', 1550, true),
  ('Whispergust Mote', 'common', 1560, true),
  ('Widemouth Bucket', 'common', 1570, true),
  ('Williwig''s Time Stopper', 'common', 1580, true),
  ('Wispy Sour', 'common', 1590, true),
  ('Abjurer''s Bangle', 'uncommon', 10, true),
  ('Acorn Charm', 'uncommon', 20, true),
  ('Adamantine Armor', 'uncommon', 30, true),
  ('Alchemist''s Potion Belt', 'uncommon', 40, true),
  ('Alchemy Jug', 'uncommon', 50, true),
  ('Alchemy Jug (Blue)', 'uncommon', 60, true),
  ('Alchemy Jug (Orange)', 'uncommon', 70, true),
  ('Ambitious Medic''s Box', 'uncommon', 80, true),
  ('Ammunition +1', 'uncommon', 90, true),
  ('Amulet of Buoyancy', 'uncommon', 100, true),
  ('Amulet of Proof Against Detection and Location', 'uncommon', 110, true),
  ('Amulet of the Drunkard', 'uncommon', 120, true),
  ('Angler''s Armor', 'uncommon', 130, true),
  ('Angler''s Worldly Fisher', 'uncommon', 140, true),
  ('Arcanist''s Magnificent Magnifier', 'uncommon', 150, true),
  ('Armor Of Fungal Spores', 'uncommon', 160, true),
  ('Armor of the Fallen', 'uncommon', 170, true),
  ('Armor of Weightlessness', 'uncommon', 180, true),
  ('Arrow of Anchoring', 'uncommon', 190, true),
  ('Ashen Katana +1', 'uncommon', 200, true),
  ('Ashen Kunai +1', 'uncommon', 210, true),
  ('Ashen Kusarigama +1', 'uncommon', 220, true),
  ('Ashen Naginata +1', 'uncommon', 230, true),
  ('Ashen Odachi +1', 'uncommon', 240, true),
  ('Ashen Tanegashima +1', 'uncommon', 250, true),
  ('Ashen Yumi +1', 'uncommon', 260, true),
  ('Astronomer''s Boon', 'uncommon', 270, true),
  ('Badge of the Savant', 'uncommon', 280, true),
  ('Bag of Bounty', 'uncommon', 290, true),
  ('Bag of Holding', 'uncommon', 300, true),
  ('Bag of Tricks', 'uncommon', 310, true),
  ('Balance of Harmony', 'uncommon', 320, true),
  ('Ballista Prosthesis', 'uncommon', 330, true),
  ('Balloon Pack', 'uncommon', 340, true),
  ('Bane Shield', 'uncommon', 350, true),
  ('Barrier Tattoo', 'uncommon', 360, true),
  ('Battlechef Field Dresser', 'uncommon', 370, true),
  ('Beard Cannon', 'uncommon', 380, true),
  ('Bellhop Topper', 'uncommon', 390, true),
  ('Blasted Goggles', 'uncommon', 400, true),
  ('Blood of the Lycanthrope Antidote', 'uncommon', 410, true),
  ('Blood Spear', 'uncommon', 420, true),
  ('Bloodhound Amulet', 'uncommon', 430, true),
  ('Bloodmire Phiale', 'uncommon', 440, true),
  ('Bloodrage Greataxe', 'uncommon', 450, true),
  ('Bloodthirsty Bistoury', 'uncommon', 460, true),
  ('Book of Clothier''s Croquis', 'uncommon', 470, true),
  ('Boomerang Shield', 'uncommon', 480, true),
  ('Boots of Elvenkind', 'uncommon', 490, true),
  ('Boots of Striding and Springing', 'uncommon', 500, true),
  ('Boots of the Vigilant', 'uncommon', 510, true),
  ('Boots of the Winterlands', 'uncommon', 520, true),
  ('Bottled Breath', 'uncommon', 530, true),
  ('Bracers of Archery', 'uncommon', 540, true),
  ('Bramble Buckler', 'uncommon', 550, true),
  ('Brawler''s Ring', 'uncommon', 560, true),
  ('Brooch of Living Essence', 'uncommon', 570, true),
  ('Brooch of Shielding', 'uncommon', 580, true),
  ('Broom of Flying', 'uncommon', 590, true),
  ('Brutal Macuahuitl', 'uncommon', 600, true),
  ('Bulette Bulwark', 'uncommon', 610, true),
  ('Burrage’s Collegiate Case', 'uncommon', 620, true),
  ('Caltrooze', 'uncommon', 630, true),
  ('Camper''s Respite', 'uncommon', 640, true),
  ('Candleflame Bow', 'uncommon', 650, true),
  ('Canister of Vreyval''s Soothing Tea', 'uncommon', 660, true),
  ('Cap of Water Breathing', 'uncommon', 670, true),
  ('Card Sharp''s Deck', 'uncommon', 680, true),
  ('Celestial Sunrise (Uncommon)', 'uncommon', 690, true),
  ('Circlet of Blasting', 'uncommon', 700, true),
  ('Circlet of Human Perfection', 'uncommon', 710, true),
  ('Claymore of the Great Badger', 'uncommon', 720, true),
  ('Cloak of Elvenkind', 'uncommon', 730, true),
  ('Cloak of Protection', 'uncommon', 740, true),
  ('Cloak of the Manta Ray', 'uncommon', 750, true),
  ('Clockwork Earwig', 'uncommon', 760, true),
  ('Clockwork Mend-A-Pillar', 'uncommon', 770, true),
  ('Club of Dancing', 'uncommon', 780, true),
  ('Club of the Forest Drake', 'uncommon', 790, true),
  ('Club of the Rook', 'uncommon', 800, true),
  ('Coiling Grasp Tattoo', 'uncommon', 810, true),
  ('Coin of Decisionry (Rank 3)', 'uncommon', 820, true),
  ('Courtesan''s Fanblade', 'uncommon', 830, true),
  ('Covolt Dagger', 'uncommon', 840, true),
  ('Cracked Driftglobe', 'uncommon', 850, true),
  ('Cuff of Captions', 'uncommon', 860, true),
  ('Cursed Luckstone', 'uncommon', 870, true),
  ('Dagger of First Light', 'uncommon', 880, true),
  ('Dark Mantle', 'uncommon', 890, true),
  ('Decanter of Endless Water', 'uncommon', 900, true),
  ('Deck of Illusions', 'uncommon', 910, true),
  ('Deck Of Miscellany', 'uncommon', 920, true),
  ('Deck Of Wonder', 'uncommon', 930, true),
  ('Detective''s Notebook', 'uncommon', 940, true),
  ('Direstone Dwarven Key', 'uncommon', 950, true),
  ('Documancy Satchel (Rank 3)', 'uncommon', 960, true),
  ('Dominic’s Field Guide to Language', 'uncommon', 970, true),
  ('Doss Lute', 'uncommon', 980, true),
  ('Doubloon Diver''s Goggles', 'uncommon', 990, true),
  ('Dragon Vessel (Slumbering)', 'uncommon', 1000, true),
  ('Dragon''s Wrath (Slumbering)', 'uncommon', 1010, true),
  ('Dragon-Touched Focus (Slumbering)', 'uncommon', 1020, true),
  ('Dramus''s Dancing Shoes', 'uncommon', 1030, true),
  ('Dried Leech', 'uncommon', 1040, true),
  ('Driftglobe', 'uncommon', 1050, true),
  ('Dusk Dagger', 'uncommon', 1060, true),
  ('Dust of Deliciousness', 'uncommon', 1070, true),
  ('Dust of Disappearance', 'uncommon', 1080, true),
  ('Dust of Dryness', 'uncommon', 1090, true),
  ('Dust of Sneezing and Choking', 'uncommon', 1100, true),
  ('Ear Cuff of the Climber', 'uncommon', 1110, true),
  ('Earworm', 'uncommon', 1120, true),
  ('Echo Stone', 'uncommon', 1130, true),
  ('Eclipse Spear', 'uncommon', 1140, true),
  ('Egg of Primal Water', 'uncommon', 1150, true),
  ('Ehagan''s Moving Ladder', 'uncommon', 1160, true),
  ('Elder Cartographer’s Glossography', 'uncommon', 1170, true),
  ('Eldritch Claw Tattoo', 'uncommon', 1180, true),
  ('Elemental Gem', 'uncommon', 1190, true),
  ('Emerald Pen', 'uncommon', 1200, true),
  ('Enspelled Armor(1st lvl spell)', 'uncommon', 1210, true),
  ('Enspelled Armor(Cantrip)', 'uncommon', 1220, true),
  ('Enspelled Staff(1st lvl spell)', 'uncommon', 1230, true),
  ('Enspelled Staff(Cantrip)', 'uncommon', 1240, true),
  ('Enspelled Weapon(1st lvl spell)', 'uncommon', 1250, true),
  ('Enspelled Weapon(Cantrip)', 'uncommon', 1260, true),
  ('Eversmoking Bottle', 'uncommon', 1270, true),
  ('Evoker''s Exchange', 'uncommon', 1280, true),
  ('Eyedrops of Clarity', 'uncommon', 1290, true),
  ('Eyes of Charming', 'uncommon', 1300, true),
  ('Eyes of Minute Seeing', 'uncommon', 1310, true),
  ('Eyes of the Beheld', 'uncommon', 1320, true),
  ('Eyes of the Eagle', 'uncommon', 1330, true),
  ('Fabulist Gem', 'uncommon', 1340, true),
  ('Felling Greataxe', 'uncommon', 1350, true),
  ('Feywatch Shield', 'uncommon', 1360, true),
  ('Feywild Shard', 'uncommon', 1370, true),
  ('Feywood Ivy', 'uncommon', 1380, true),
  ('Figurine of Wondrous Power (Silver Raven)', 'uncommon', 1390, true),
  ('Finder''s Goggles', 'uncommon', 1400, true),
  ('Fists of the Guiding Star', 'uncommon', 1410, true),
  ('Flamebreather Staff', 'uncommon', 1420, true),
  ('Flood Pauldron', 'uncommon', 1430, true),
  ('Fochlucan Bandore', 'uncommon', 1440, true),
  ('Focus Circlet', 'uncommon', 1450, true),
  ('Forgekeeper''s Spark', 'uncommon', 1460, true),
  ('Gauntlets of Deliverance', 'uncommon', 1470, true),
  ('Gauntlets of Ogre Power', 'uncommon', 1480, true),
  ('Gelatinous Whip', 'uncommon', 1490, true),
  ('Gem of Brightness', 'uncommon', 1500, true),
  ('Glamerweave (Uncommon)', 'uncommon', 1510, true),
  ('Glass Carver', 'uncommon', 1520, true),
  ('Gloves of Amphibios', 'uncommon', 1530, true),
  ('Gloves of Missile Snaring', 'uncommon', 1540, true),
  ('Gloves of Swimming and Climbing', 'uncommon', 1550, true),
  ('Gloves of the Great Badger', 'uncommon', 1560, true),
  ('Gloves of Thievery', 'uncommon', 1570, true),
  ('Gnashing Key', 'uncommon', 1580, true),
  ('Goggles of Night', 'uncommon', 1590, true),
  ('Goggles of Object Reading', 'uncommon', 1600, true),
  ('Great Owl''s Shroud', 'uncommon', 1610, true),
  ('Griffon Component Pack', 'uncommon', 1620, true),
  ('Guardian Emblem', 'uncommon', 1630, true),
  ('Guild Keyrune (Rakdos)', 'uncommon', 1640, true),
  ('Guild Keyrune (Simic)', 'uncommon', 1650, true),
  ('Guild Signet', 'uncommon', 1660, true),
  ('Gusting Blowgun', 'uncommon', 1670, true),
  ('Hadiya''s Handy Quill', 'uncommon', 1680, true),
  ('Halberd of the Reforged Soul +1', 'uncommon', 1690, true),
  ('Harvest', 'uncommon', 1700, true),
  ('Hat of Disguise', 'uncommon', 1710, true),
  ('Hat of the Sanguine Coven', 'uncommon', 1720, true),
  ('Headband of intellect', 'uncommon', 1730, true),
  ('Headdress of the Serpent King', 'uncommon', 1740, true),
  ('Headhunter''s Bullseye Lantern', 'uncommon', 1750, true),
  ('Hedonic Motivator', 'uncommon', 1760, true),
  ('Hellfire Weapon', 'uncommon', 1770, true),
  ('Helm of Comprehend Languages', 'uncommon', 1780, true),
  ('Helm of Telepathy', 'uncommon', 1790, true),
  ('Helm of Underwater Action', 'uncommon', 1800, true),
  ('Hideaway Vase', 'uncommon', 1810, true),
  ('Hoarder''s Haul (Uncommon)', 'uncommon', 1820, true),
  ('House Of Cards', 'uncommon', 1830, true),
  ('Hurler''s Gloves', 'uncommon', 1840, true),
  ('Hushed Ring', 'uncommon', 1850, true),
  ('Immovable Rod', 'uncommon', 1860, true),
  ('Infernal Puzzle Box', 'uncommon', 1870, true),
  ('Inquisitive’s Goggles', 'uncommon', 1880, true),
  ('Insignia of Claws', 'uncommon', 1890, true),
  ('Javelin of Lightning', 'uncommon', 1900, true),
  ('Jo''Catian Denier', 'uncommon', 1910, true),
  ('Jo''Catian Rebuker', 'uncommon', 1920, true),
  ('Keoghtom’s Ointment', 'uncommon', 1930, true),
  ('Kestra''s Bent Spoon', 'uncommon', 1940, true),
  ('Knave’s Eye Patch', 'uncommon', 1950, true),
  ('Lantern of Revealing', 'uncommon', 1960, true),
  ('Life Tether Ankh', 'uncommon', 1970, true),
  ('Lightbringer', 'uncommon', 1980, true),
  ('Living Gloves', 'uncommon', 1990, true),
  ('Living Loot Satchel (Rank 2)', 'uncommon', 2000, true),
  ('Locket of the Stolen Heart', 'uncommon', 2010, true),
  ('Lorehold Primer', 'uncommon', 2020, true),
  ('Luckleaf', 'uncommon', 2030, true),
  ('Luna Moth Cape', 'uncommon', 2040, true),
  ('Lunar Weapon', 'uncommon', 2050, true),
  ('Lupine Mask', 'uncommon', 2060, true),
  ('Mac-Fuirmidh Cittern', 'uncommon', 2070, true),
  ('Mace of the Pumpkin King', 'uncommon', 2080, true),
  ('Magentan Sun-Saw (Uncommon)', 'uncommon', 2090, true),
  ('Mandible Bident', 'uncommon', 2100, true),
  ('Mariner’s Armor', 'uncommon', 2110, true),
  ('Marlin Lunger', 'uncommon', 2120, true),
  ('Mask of the Beast', 'uncommon', 2130, true),
  ('Masks of the Sacred Beasts (Lion)', 'uncommon', 2140, true),
  ('Medallion of Thoughts', 'uncommon', 2150, true),
  ('Medusan Signet', 'uncommon', 2160, true),
  ('Mimicloak', 'uncommon', 2170, true),
  ('Mind Carapace Armor', 'uncommon', 2180, true),
  ('Mithral Armor', 'uncommon', 2190, true),
  ('Mizzium Apparatus', 'uncommon', 2200, true),
  ('Mourningsteel Ghost Candle', 'uncommon', 2210, true),
  ('Mummy Rot Antidote', 'uncommon', 2220, true),
  ('Murk Blowgun', 'uncommon', 2230, true),
  ('Nature''s Mantle', 'uncommon', 2240, true),
  ('Necklace of Adaptation', 'uncommon', 2250, true),
  ('Night Caller', 'uncommon', 2260, true),
  ('Night Owl''s Half-Moon Spectacles', 'uncommon', 2270, true),
  ('No-Stones', 'uncommon', 2280, true),
  ('Obviator’s Lenses (Rank 2)', 'uncommon', 2290, true),
  ('Occultant Abacus (Rank 2)', 'uncommon', 2300, true),
  ('Oil of Slipperiness', 'uncommon', 2310, true),
  ('Ol'' Stumpy', 'uncommon', 2320, true),
  ('Orner''s Venomous Crossbow', 'uncommon', 2330, true),
  ('Overseer''s Spade', 'uncommon', 2340, true),
  ('Owlbear Leather Armor', 'uncommon', 2350, true),
  ('Paper Bird', 'uncommon', 2360, true),
  ('Pearl of Power', 'uncommon', 2370, true),
  ('Pegasus Quill', 'uncommon', 2380, true),
  ('Periapt of Health', 'uncommon', 2390, true),
  ('Periapt of Wound Closure', 'uncommon', 2400, true),
  ('Phantom Walkers', 'uncommon', 2410, true),
  ('Philter of Love', 'uncommon', 2420, true),
  ('Pipes of Haunting', 'uncommon', 2430, true),
  ('Pipes of the Sewers', 'uncommon', 2440, true),
  ('Pisces Shield', 'uncommon', 2450, true),
  ('Piwafwi (Cloak of Elvenkind)', 'uncommon', 2460, true),
  ('Plate Of Knight''s Fellowship', 'uncommon', 2470, true),
  ('Pollinator Carapace', 'uncommon', 2480, true),
  ('Pollinator Pants', 'uncommon', 2490, true),
  ('Pollinator Visor', 'uncommon', 2500, true),
  ('Portfolio Keeper (Rank 2)', 'uncommon', 2510, true),
  ('Potion of Animal Friendship', 'uncommon', 2520, true),
  ('Potion of Fire Breath', 'uncommon', 2530, true),
  ('Potion of Giant Strength (Hill Giant)', 'uncommon', 2540, true),
  ('Potion of Growth', 'uncommon', 2550, true),
  ('Potion of Healing (Greater)', 'uncommon', 2560, true),
  ('Potion of Poison', 'uncommon', 2570, true),
  ('Potion of Resistance', 'uncommon', 2580, true),
  ('Potion of Water Breathing', 'uncommon', 2590, true),
  ('Prehistoric Figurines of Wondrous Power', 'uncommon', 2600, true),
  ('Prismari Primer', 'uncommon', 2610, true),
  ('Propellor Helm', 'uncommon', 2620, true),
  ('Prying Mace', 'uncommon', 2630, true),
  ('Psi Crystal', 'uncommon', 2640, true),
  ('Pyroconverger', 'uncommon', 2650, true),
  ('Quandrix Primer', 'uncommon', 2660, true),
  ('Quiver of Ehlonna', 'uncommon', 2670, true),
  ('Rejuvenating Draft (Uncommon)', 'uncommon', 2680, true),
  ('Reliquary of Holy Memories', 'uncommon', 2690, true),
  ('Riff''s Dimensional Ripper', 'uncommon', 2700, true),
  ('Ring of Healer''s Heroism', 'uncommon', 2710, true),
  ('Ring of Jumping', 'uncommon', 2720, true),
  ('Ring of Mind Shielding', 'uncommon', 2730, true),
  ('Ring of Obscuring', 'uncommon', 2740, true),
  ('Ring Of Puzzler''s Wit', 'uncommon', 2750, true),
  ('Ring of Rituals', 'uncommon', 2760, true),
  ('Ring of Stolen Alacrity', 'uncommon', 2770, true),
  ('Ring of Swimming', 'uncommon', 2780, true),
  ('Ring of the Mute Mage', 'uncommon', 2790, true),
  ('Ring of Truth Telling', 'uncommon', 2800, true),
  ('Ring of Volleys', 'uncommon', 2810, true),
  ('Ring of Warmth', 'uncommon', 2820, true),
  ('Ring of Water Walking', 'uncommon', 2830, true),
  ('Rings of Shared Suffering', 'uncommon', 2840, true),
  ('Roaring Whip', 'uncommon', 2850, true),
  ('Robe of Serpents', 'uncommon', 2860, true),
  ('Robe of Useful Items', 'uncommon', 2870, true),
  ('Rod of Mercurial Form', 'uncommon', 2880, true),
  ('Rod of Retribution', 'uncommon', 2890, true),
  ('Rod of Thought Projection', 'uncommon', 2900, true),
  ('Rope of Climbing', 'uncommon', 2910, true),
  ('Rust Arrow', 'uncommon', 2920, true),
  ('Saddle of the Cavalier', 'uncommon', 2930, true),
  ('Sagittarian Vestments', 'uncommon', 2940, true),
  ('Satchel of Beast Chow', 'uncommon', 2950, true),
  ('Scaled Ornament (Slumbering)', 'uncommon', 2960, true),
  ('Scorpio Armor', 'uncommon', 2970, true),
  ('Scorpion Lasher', 'uncommon', 2980, true),
  ('Scroll of Mapping (Uncommon)', 'uncommon', 2990, true),
  ('Second Fiddle', 'uncommon', 3000, true),
  ('Seeker Dart', 'uncommon', 3010, true),
  ('Seeker''s Compass', 'uncommon', 3020, true),
  ('Seer''s Starlight Cloak', 'uncommon', 3030, true),
  ('Sending Stones', 'uncommon', 3040, true),
  ('Sentinel Shield', 'uncommon', 3050, true),
  ('Serpent Scale Armor', 'uncommon', 3060, true),
  ('Shadow Weaver''s Guise', 'uncommon', 3070, true),
  ('Shatterspike', 'uncommon', 3080, true),
  ('Shield Of The Tortoise', 'uncommon', 3090, true),
  ('Shifter''s Shine (Uncommon)', 'uncommon', 3100, true),
  ('Silver Eagle Studded Cuirass', 'uncommon', 3110, true),
  ('Silverquill Primer', 'uncommon', 3120, true),
  ('Sir Varion''s Helm', 'uncommon', 3130, true),
  ('Sir Varion''s Lance', 'uncommon', 3140, true),
  ('Sir Varion''s Mantle', 'uncommon', 3150, true),
  ('Sir Varion''s Shield', 'uncommon', 3160, true),
  ('Skyblinder Staff', 'uncommon', 3170, true),
  ('Sling Of Giant Felling', 'uncommon', 3180, true),
  ('Slippers of Spider Climbing', 'uncommon', 3190, true),
  ('Smokepowder', 'uncommon', 3200, true),
  ('Snake Charmer''s Flute', 'uncommon', 3210, true),
  ('Solar Amulet', 'uncommon', 3220, true),
  ('Soul Coin', 'uncommon', 3230, true),
  ('Spell Gem (Lapis Lazuli)', 'uncommon', 3240, true),
  ('Spell Gem (Obsidian)', 'uncommon', 3250, true),
  ('Spell Scroll (2nd Level)', 'uncommon', 3260, true),
  ('Spell Scroll (3rd Level)', 'uncommon', 3270, true),
  ('Spies'' Murmur', 'uncommon', 3280, true),
  ('Splinter Bow', 'uncommon', 3290, true),
  ('Staff of Cubic Cultivation', 'uncommon', 3300, true),
  ('Staff of the Adder', 'uncommon', 3310, true),
  ('Staff of the Dream Shepherd', 'uncommon', 3320, true),
  ('Staff of the Python', 'uncommon', 3330, true),
  ('Staff of the Vineyard', 'uncommon', 3340, true),
  ('Stone of Good Luck (Luckstone)', 'uncommon', 3350, true),
  ('Stone of Ill Luck', 'uncommon', 3360, true),
  ('Stonemason''s Companion', 'uncommon', 3370, true),
  ('Storm Boomerang', 'uncommon', 3380, true),
  ('Stuffy Familiar', 'uncommon', 3390, true),
  ('Sword of Vengeance', 'uncommon', 3400, true),
  ('Tattoo, Spellwrought (2nd Level)', 'uncommon', 3410, true),
  ('Tattoo, Spellwrought (3rd Level)', 'uncommon', 3420, true),
  ('Thessaltoxin Antidote', 'uncommon', 3430, true),
  ('Thomas''s Dimensional Trousers', 'uncommon', 3440, true),
  ('Titan Cricket Greaves', 'uncommon', 3450, true),
  ('Trampling Crossbow', 'uncommon', 3460, true),
  ('Travel Alchemical Kit', 'uncommon', 3470, true),
  ('Trident of Fish Command', 'uncommon', 3480, true),
  ('Umbrella of Shielding', 'uncommon', 3490, true),
  ('Vain Virtuoso''s Violin', 'uncommon', 3500, true),
  ('Wand of Dowsing', 'uncommon', 3510, true),
  ('Wand of Magic Detection', 'uncommon', 3520, true),
  ('Wand of Magic Missiles', 'uncommon', 3530, true),
  ('Wand of Secrets', 'uncommon', 3540, true),
  ('Wand of the War Mage +1', 'uncommon', 3550, true),
  ('Wand of Web', 'uncommon', 3560, true),
  ('Waterskin of Voices', 'uncommon', 3570, true),
  ('Weapon of Verdict', 'uncommon', 3580, true),
  ('Weapon of Warning', 'uncommon', 3590, true),
  ('Weaving Wasp Needles', 'uncommon', 3600, true),
  ('Wheel of Wind and Water', 'uncommon', 3610, true),
  ('Whirlpool Dart', 'uncommon', 3620, true),
  ('Whisper Jar (Rank 2)', 'uncommon', 3630, true),
  ('Wildskin Armor', 'uncommon', 3640, true),
  ('Wildspace Orrery', 'uncommon', 3650, true),
  ('Wind Fan', 'uncommon', 3660, true),
  ('Winged Ammunition', 'uncommon', 3670, true),
  ('Winged Boots', 'uncommon', 3680, true),
  ('Wingwear', 'uncommon', 3690, true),
  ('Winter''s Dark Bite', 'uncommon', 3700, true),
  ('Wisp Cloak', 'uncommon', 3710, true),
  ('Wispy Sour', 'uncommon', 3720, true),
  ('Witherbloom Primer', 'uncommon', 3730, true),
  ('Abjurer''s Bangle', 'rare', 10, true),
  ('Acheron Blade', 'rare', 20, true),
  ('Adventurer''s Overcoat', 'rare', 30, true),
  ('Aged Goodberry Wine', 'rare', 40, true),
  ('Air Render', 'rare', 50, true),
  ('Alchemical Compendium', 'rare', 60, true),
  ('All Purpose Tool +2', 'rare', 70, true),
  ('Ammunition +2', 'rare', 80, true),
  ('Amulet of Health', 'rare', 90, true),
  ('Amulet of Immutability', 'rare', 100, true),
  ('Amulet of Protection From Turning', 'rare', 110, true),
  ('Amulet of the Devout +2', 'rare', 120, true),
  ('Amulet of the Lycanthrope', 'rare', 130, true),
  ('Amulet of the Sentinel', 'rare', 140, true),
  ('Appraiser''s Eye', 'rare', 150, true),
  ('Arcane Grimoire +2', 'rare', 160, true),
  ('Arcanist Gauntlets', 'rare', 170, true),
  ('Arcanist''s Scribing Wand', 'rare', 180, true),
  ('Armor +1', 'rare', 190, true),
  ('Armor of Icarus', 'rare', 200, true),
  ('Armor of Resistance', 'rare', 210, true),
  ('Armor of Vulnerability', 'rare', 220, true),
  ('Arrow-Catching Shield', 'rare', 230, true),
  ('Ashen Katana +2', 'rare', 240, true),
  ('Ashen Kunai +2', 'rare', 250, true),
  ('Ashen Kusarigama +2', 'rare', 260, true),
  ('Ashen Naginata +2', 'rare', 270, true),
  ('Ashen Odachi +2', 'rare', 280, true),
  ('Ashen Tanegashima +2', 'rare', 290, true),
  ('Ashen Yumi +2', 'rare', 300, true),
  ('Astral Caltrops', 'rare', 310, true),
  ('Astral Shard', 'rare', 320, true),
  ('Astromancy Archive', 'rare', 330, true),
  ('Atlas of Endless Horizons', 'rare', 340, true),
  ('Badge of the Watch', 'rare', 350, true),
  ('Badge of the Wayfarer', 'rare', 360, true),
  ('Bag of Beans', 'rare', 370, true),
  ('Bandolier of the Elements', 'rare', 380, true),
  ('Banner of the Krig Rune', 'rare', 390, true),
  ('Barrier Tattoo', 'rare', 400, true),
  ('Bartender''s Armistice', 'rare', 410, true),
  ('Battering Shield', 'rare', 420, true),
  ('Bead of Force', 'rare', 430, true),
  ('Beads of Meditation', 'rare', 440, true),
  ('Bell Branch', 'rare', 450, true),
  ('Belt of Dwarvenkind', 'rare', 460, true),
  ('Belt of Giant Strength (Hill Giant)', 'rare', 470, true),
  ('Belt of the Hell Hound', 'rare', 480, true),
  ('Berserker Axe', 'rare', 490, true),
  ('Blackthorn Spear of the Moonless Hunter', 'rare', 500, true),
  ('Blod Stone', 'rare', 510, true),
  ('Bloodmire Rod of the Witch Doctor', 'rare', 520, true),
  ('Bloodshard Trident', 'rare', 530, true),
  ('Bloodwell Vial +2', 'rare', 540, true),
  ('Bonecounter', 'rare', 550, true),
  ('Boots of Levitation', 'rare', 560, true),
  ('Boots of Speed', 'rare', 570, true),
  ('Bounder''s Ball', 'rare', 580, true),
  ('Bow Of Conflagration', 'rare', 590, true),
  ('Bow of the Cobra', 'rare', 600, true),
  ('Bow of the Eldritch Archer', 'rare', 610, true),
  ('Bow of the Twilight Valkyrie', 'rare', 620, true),
  ('Bowl of Commanding Water Elementals', 'rare', 630, true),
  ('Bracer of Flying Daggers', 'rare', 640, true),
  ('Bracers of Defense', 'rare', 650, true),
  ('Bracers of the Iron Octopus', 'rare', 660, true),
  ('Brazier of Commanding Fire Elementals', 'rare', 670, true),
  ('Breastplate Of Balance', 'rare', 680, true),
  ('Bridle of Capturing', 'rare', 690, true),
  ('Butcher''s Bib', 'rare', 700, true),
  ('Caduceus Flail', 'rare', 710, true),
  ('Canaith Mandolin', 'rare', 720, true),
  ('Cape of the Mountebank', 'rare', 730, true),
  ('Captain''s Pride', 'rare', 740, true),
  ('Cauldron of Plenty', 'rare', 750, true),
  ('Censer of Controlling Air Elementals', 'rare', 760, true),
  ('Chain Devil Gloves', 'rare', 770, true),
  ('Champion''s Greatbow', 'rare', 780, true),
  ('Charm of Plant Command', 'rare', 790, true),
  ('Chi-Balancing Tea', 'rare', 800, true),
  ('Chime of Opening', 'rare', 810, true),
  ('Chimeric Collar', 'rare', 820, true),
  ('Chromatic Obsidian Greataxe', 'rare', 830, true),
  ('Claw of the Wyrm Rune', 'rare', 840, true),
  ('Claws of the Umber Hulk', 'rare', 850, true),
  ('Cli Lyre', 'rare', 860, true),
  ('Cloak of Displacement', 'rare', 870, true),
  ('Cloak of the Bat', 'rare', 880, true),
  ('Clockwork Colony Toolbox', 'rare', 890, true),
  ('Coat of the Crest', 'rare', 900, true),
  ('Coldfire Anvil', 'rare', 910, true),
  ('Comet Ballista', 'rare', 920, true),
  ('Conspirator''s Coat', 'rare', 930, true),
  ('Contingency Band', 'rare', 940, true),
  ('Corpse Slayer', 'rare', 950, true),
  ('Cottage Chest', 'rare', 960, true),
  ('Covolt Scythe', 'rare', 970, true),
  ('Crown of the Mindmaster Matriarch', 'rare', 980, true),
  ('Crown of the Wrath Bringer', 'rare', 990, true),
  ('Crystal Blade', 'rare', 1000, true),
  ('Cube of Cubes', 'rare', 1010, true),
  ('Cube of Force', 'rare', 1020, true),
  ('Cube of Teleportation', 'rare', 1030, true),
  ('Daern’s instant Fortress', 'rare', 1040, true),
  ('Dagger of Blindsight', 'rare', 1050, true),
  ('Dagger of Denial', 'rare', 1060, true),
  ('Dagger of Venom', 'rare', 1070, true),
  ('Dawn and Dusk', 'rare', 1080, true),
  ('Deathloop Watch', 'rare', 1090, true),
  ('Deck Of Oracles', 'rare', 1100, true),
  ('Delver''s Claws', 'rare', 1110, true),
  ('Demon Skin', 'rare', 1120, true),
  ('Devastation Orb', 'rare', 1130, true),
  ('Devotee''s Censer', 'rare', 1140, true),
  ('Diabolic Conduit +2', 'rare', 1150, true),
  ('Dimensional Shackles', 'rare', 1160, true),
  ('Direstone Runic Wand', 'rare', 1170, true),
  ('Diviner''s Dice', 'rare', 1180, true),
  ('Djinn and Tonic (Rare)', 'rare', 1190, true),
  ('Docent', 'rare', 1200, true),
  ('Documancy Satchel (Rank 4)', 'rare', 1210, true),
  ('Dodecahedron of Doom', 'rare', 1220, true),
  ('Donjon''s Sundering Sphere', 'rare', 1230, true),
  ('Doom Bloom', 'rare', 1240, true),
  ('Dragon Slayer', 'rare', 1250, true),
  ('Dragon Vessel (Stirring)', 'rare', 1260, true),
  ('Dragon Wing Bow', 'rare', 1270, true),
  ('Dragon''s Wrath (Stirring)', 'rare', 1280, true),
  ('Dragon-Touched Focus (Stirring)', 'rare', 1290, true),
  ('Dragonband', 'rare', 1300, true),
  ('Dragonbreath Ammunition', 'rare', 1310, true),
  ('Dragonguard', 'rare', 1320, true),
  ('Dragonhide Belt +2', 'rare', 1330, true),
  ('Dragontooth Dagger', 'rare', 1340, true),
  ('Dream Saber', 'rare', 1350, true),
  ('Dress of Defense', 'rare', 1360, true),
  ('Dune Cowl', 'rare', 1370, true),
  ('Duplicitous Manuscript', 'rare', 1380, true),
  ('Dusk Cleaver', 'rare', 1390, true),
  ('Dusk Dagger', 'rare', 1400, true),
  ('Dwarven Boozehound''s Backpack', 'rare', 1410, true),
  ('Eagle Whistle', 'rare', 1420, true),
  ('Earthboard', 'rare', 1430, true),
  ('Elder Sequoia Scale Mail', 'rare', 1440, true),
  ('Eldritch Bident', 'rare', 1450, true),
  ('Elemental Essence Shard', 'rare', 1460, true),
  ('Elixir of Health', 'rare', 1470, true),
  ('Elven Chain', 'rare', 1480, true),
  ('Enspelled Armor(2nd lvl spell)', 'rare', 1490, true),
  ('Enspelled Armor(3rd lvl spell)', 'rare', 1500, true),
  ('Enspelled Staff(2nd lvl spell)', 'rare', 1510, true),
  ('Enspelled Staff(3rd lvl spell)', 'rare', 1520, true),
  ('Enspelled Weapon(2nd lvl spell)', 'rare', 1530, true),
  ('Enspelled Weapon(3rd lvl spell)', 'rare', 1540, true),
  ('Everglacier Prosthesis', 'rare', 1550, true),
  ('Faeflame Torch', 'rare', 1560, true),
  ('Failed Experiment Wand', 'rare', 1570, true),
  ('Failed Purity Spear', 'rare', 1580, true),
  ('Far Realm Shard', 'rare', 1590, true),
  ('Fate Dealer''s Deck', 'rare', 1600, true),
  ('Feather of Diatryma Summoning', 'rare', 1610, true),
  ('Feywrought Armor', 'rare', 1620, true),
  ('Figurine of Wondrous Power (Bronze Griffon)', 'rare', 1630, true),
  ('Figurine of Wondrous Power (Ebony Fly)', 'rare', 1640, true),
  ('Figurine of Wondrous Power (Golden Lions)', 'rare', 1650, true),
  ('Figurine of Wondrous Power (Ivory Goats)', 'rare', 1660, true),
  ('Figurine of Wondrous Power (Marble Elephant)', 'rare', 1670, true),
  ('Figurine of Wondrous Power (Onyx Dog)', 'rare', 1680, true),
  ('Figurine of Wondrous Power (Serpentine Owl)', 'rare', 1690, true),
  ('Flame Tongue', 'rare', 1700, true),
  ('Flamefriend Lantern', 'rare', 1710, true),
  ('Flying Chariot', 'rare', 1720, true),
  ('Focus Breaker', 'rare', 1730, true),
  ('Folding Boat', 'rare', 1740, true),
  ('Forgework Dragon Shield', 'rare', 1750, true),
  ('Fulminating Treatise', 'rare', 1760, true),
  ('Fused Chimeric Hide', 'rare', 1770, true),
  ('Galder’s Bubble Pipe', 'rare', 1780, true),
  ('Gambler’s Blade', 'rare', 1790, true),
  ('Gauntlets of Consecrated Sacrifice', 'rare', 1800, true),
  ('Gauntlets of Eldritch Ferocity', 'rare', 1810, true),
  ('Gauntlets of Flaming Fury', 'rare', 1820, true),
  ('Gavel of the Venn Rune', 'rare', 1830, true),
  ('Gem of Seeing', 'rare', 1840, true),
  ('Gentleman''s Saber', 'rare', 1850, true),
  ('Ghost Lantern', 'rare', 1860, true),
  ('Gi of Shifting Seasons', 'rare', 1870, true),
  ('Giant Slayer', 'rare', 1880, true),
  ('Giantcraft Ambusher', 'rare', 1890, true),
  ('Glamoured Studded Leather', 'rare', 1900, true),
  ('Glimmering Moonbow', 'rare', 1910, true),
  ('Gloomwrought Armor', 'rare', 1920, true),
  ('Gloves of Healing', 'rare', 1930, true),
  ('Glowrune Pigment', 'rare', 1940, true),
  ('Golem Sapper', 'rare', 1950, true),
  ('Grasping Whip', 'rare', 1960, true),
  ('Guild Keyrune (Azorius)', 'rare', 1970, true),
  ('Guild Keyrune (Boros)', 'rare', 1980, true),
  ('Guild Keyrune (Gruul)', 'rare', 1990, true),
  ('Guild Keyrune (Izzet)', 'rare', 2000, true),
  ('Guild Keyrune (Orzhov)', 'rare', 2010, true),
  ('Guild Keyrune (Selesnya)', 'rare', 2020, true),
  ('Gulthias Staff', 'rare', 2030, true),
  ('Halberd of the Reforged Soul +2', 'rare', 2040, true),
  ('Harbinger''s Flail', 'rare', 2050, true),
  ('Heart Weaver’s Primer', 'rare', 2060, true),
  ('Heavenly Chalice', 'rare', 2070, true),
  ('Heavy Golem Armor', 'rare', 2080, true),
  ('Hell Hound Cloak', 'rare', 2090, true),
  ('Helm of Teleportation', 'rare', 2100, true),
  ('Helm of the Gods', 'rare', 2110, true),
  ('Heward’s Handy Haversack', 'rare', 2120, true),
  ('Hide of the Brimstone Behemoth +1', 'rare', 2130, true),
  ('Hoarder''s Haul (Rare)', 'rare', 2140, true),
  ('Holy Symbol of Ravenkind', 'rare', 2150, true),
  ('Homeroot', 'rare', 2160, true),
  ('Homeward Boots', 'rare', 2170, true),
  ('Hook of Fisher''s Delight', 'rare', 2180, true),
  ('Horatio’s Impossible Ship in a Bottle', 'rare', 2190, true),
  ('Horn of Blasting', 'rare', 2200, true),
  ('Horn of Valhalla (brass)', 'rare', 2210, true),
  ('Horn of Valhalla (silver)', 'rare', 2220, true),
  ('Horseshoes of Speed', 'rare', 2230, true),
  ('Hydra Flail', 'rare', 2240, true),
  ('Inescapable Lash', 'rare', 2250, true),
  ('Insatiable Tome', 'rare', 2260, true),
  ('Ioun Stone (Awareness)', 'rare', 2270, true),
  ('Ioun Stone (Historical Knowledge)', 'rare', 2280, true),
  ('Ioun Stone (Language Knowledge)', 'rare', 2290, true),
  ('Ioun Stone (Natural Knowledge)', 'rare', 2300, true),
  ('Ioun Stone (Protection)', 'rare', 2310, true),
  ('Ioun Stone (Religious Knowledge)', 'rare', 2320, true),
  ('Ioun Stone (Reserve)', 'rare', 2330, true),
  ('Ioun Stone (Self-Preservation)', 'rare', 2340, true),
  ('Ioun Stone (Supreme Intellect)', 'rare', 2350, true),
  ('Ioun Stone (Sustenance)', 'rare', 2360, true),
  ('Iron Bands of Bilarro', 'rare', 2370, true),
  ('Ironleaf Impaler', 'rare', 2380, true),
  ('Kinetic Bowstring', 'rare', 2390, true),
  ('Lamian Facestealer', 'rare', 2400, true),
  ('Lash of Immolation', 'rare', 2410, true),
  ('Lash of the Spelldrinker', 'rare', 2420, true),
  ('Leather Golem Armor', 'rare', 2430, true),
  ('Libram of Souls and Flesh', 'rare', 2440, true),
  ('Life''s Flower Restorative', 'rare', 2450, true),
  ('Lightning Khopesh', 'rare', 2460, true),
  ('Lightscreen Hover Boots', 'rare', 2470, true),
  ('Living Loot Satchel (Rank 3)', 'rare', 2480, true),
  ('Loadstone', 'rare', 2490, true),
  ('Lyre of Building', 'rare', 2500, true),
  ('Mace of Disruption', 'rare', 2510, true),
  ('Mace of Smiting', 'rare', 2520, true),
  ('Mace of Terror', 'rare', 2530, true),
  ('Mace of the Priest', 'rare', 2540, true),
  ('Mageplate Ring', 'rare', 2550, true),
  ('Magician''s Judge', 'rare', 2560, true),
  ('Mantle of Security', 'rare', 2570, true),
  ('Mantle of Spell Resistance', 'rare', 2580, true),
  ('Masks of the Sacred Beasts (Hawk)', 'rare', 2590, true),
  ('Master’s Amulet', 'rare', 2600, true),
  ('Medusan Lavalier', 'rare', 2610, true),
  ('Medzo''s Crossbow', 'rare', 2620, true),
  ('Meta Medallion', 'rare', 2630, true),
  ('Mind Blade', 'rare', 2640, true),
  ('Mind Lash', 'rare', 2650, true),
  ('Mirror of the Past', 'rare', 2660, true),
  ('Mistwalker Armor', 'rare', 2670, true),
  ('Mithral Half Plate, +1', 'rare', 2680, true),
  ('Mizzium Armor', 'rare', 2690, true),
  ('Mizzium Mortar', 'rare', 2700, true),
  ('Molten Bronze Skin', 'rare', 2710, true),
  ('Monarch Mantle', 'rare', 2720, true),
  ('Monster Tamer''s Shield', 'rare', 2730, true),
  ('Monster Tamer''s Sword', 'rare', 2740, true),
  ('Moon Sickle +2', 'rare', 2750, true),
  ('Moonstone Bracers', 'rare', 2760, true),
  ('Mosshide Troll Belt', 'rare', 2770, true),
  ('Mourningsteel War Banner', 'rare', 2780, true),
  ('Myceliaweave Armor', 'rare', 2790, true),
  ('Necklace of Fireballs', 'rare', 2800, true),
  ('Necklace of Prayer Beads', 'rare', 2810, true),
  ('Needle of Mending', 'rare', 2820, true),
  ('Nightmare Flask', 'rare', 2830, true),
  ('Nightstalker''s Armor of the Northeastern Wind', 'rare', 2840, true),
  ('Nightstalker''s Mask', 'rare', 2850, true),
  ('Obviator’s Lenses (Rank 4)', 'rare', 2860, true),
  ('Occultant Abacus (Rank 3)', 'rare', 2870, true),
  ('Oceanic Weapon', 'rare', 2880, true),
  ('Oil of Etherealness', 'rare', 2890, true),
  ('Opal of the Ild Rune', 'rare', 2900, true),
  ('Orb of the Stein Rune', 'rare', 2910, true),
  ('Orelia''s Tome of Beast Familiars', 'rare', 2920, true),
  ('Outer Essence Shard', 'rare', 2930, true),
  ('Pack of Revisibility Bombs', 'rare', 2940, true),
  ('Pariah’s Shield', 'rare', 2950, true),
  ('Pennypuncher Slingshot', 'rare', 2960, true),
  ('Peregrine Spear', 'rare', 2970, true),
  ('Periapt of Proof Against Poison', 'rare', 2980, true),
  ('Pick and Pocket', 'rare', 2990, true),
  ('Piercer', 'rare', 3000, true),
  ('Piwafwi of Fire Resistance', 'rare', 3010, true),
  ('Planecaller’s Codex', 'rare', 3020, true),
  ('Poison Armor of Amphibios', 'rare', 3030, true),
  ('Portable Hole', 'rare', 3040, true),
  ('Portfolio Keeper (Rank 3)', 'rare', 3050, true),
  ('Portfolio Keeper (Rank 4)', 'rare', 3060, true),
  ('Potion of Aqueous Form', 'rare', 3070, true),
  ('Potion of Clairvoyance', 'rare', 3080, true),
  ('Potion of Diminution', 'rare', 3090, true),
  ('Potion of Gaseous Form', 'rare', 3100, true),
  ('Potion of Giant Strength (Fire Giant)', 'rare', 3110, true),
  ('Potion of Giant Strength (Frost or Stone Giant)', 'rare', 3120, true),
  ('Potion of Healing (Superior)', 'rare', 3130, true),
  ('Potion of Heroism', 'rare', 3140, true),
  ('Potion of Invisibility', 'rare', 3150, true),
  ('Potion of Invulnerability', 'rare', 3160, true),
  ('Potion of Maximum Power', 'rare', 3170, true),
  ('Potion of Mind Control (Beast/Person)', 'rare', 3180, true),
  ('Potion of Mind Reading', 'rare', 3190, true),
  ('Power Collar', 'rare', 3200, true),
  ('Prehistoric Figurines of Wondrous Power', 'rare', 3210, true),
  ('Professor Orb', 'rare', 3220, true),
  ('Protective Verses', 'rare', 3230, true),
  ('Prototype Thunderberd', 'rare', 3240, true),
  ('Quaal’s Feather Token', 'rare', 3250, true),
  ('Quick Change Ring', 'rare', 3260, true),
  ('Radiant Weapon', 'rare', 3270, true),
  ('Redeemer''s Regards', 'rare', 3280, true),
  ('Rejuvenating Draft (Rare)', 'rare', 3290, true),
  ('Reliquary of Holy Memories', 'rare', 3300, true),
  ('Reveler’s Concertina', 'rare', 3310, true),
  ('Rhythm-Maker''s Drum +2', 'rare', 3320, true),
  ('Rift Sheath', 'rare', 3330, true),
  ('Ring of Animal Influence', 'rare', 3340, true),
  ('Ring of Changing Shapes', 'rare', 3350, true),
  ('Ring of Evasion', 'rare', 3360, true),
  ('Ring of Feather Falling', 'rare', 3370, true),
  ('Ring of Free Action', 'rare', 3380, true),
  ('Ring of Misdirection', 'rare', 3390, true),
  ('Ring of Protection', 'rare', 3400, true),
  ('Ring of Resistance', 'rare', 3410, true),
  ('Ring of Solar''s Sight', 'rare', 3420, true),
  ('Ring of Spell Storing', 'rare', 3430, true),
  ('Ring of Temporal Salvation', 'rare', 3440, true),
  ('Ring of the Arcane Berserker', 'rare', 3450, true),
  ('Ring of the Ram', 'rare', 3460, true),
  ('Ring of X-ray Vision', 'rare', 3470, true),
  ('Rings of the True Companions', 'rare', 3480, true),
  ('Riptide Crossbow', 'rare', 3490, true),
  ('Robe of Eyes', 'rare', 3500, true),
  ('Robe of Summer', 'rare', 3510, true),
  ('Rod of Refstophobia', 'rare', 3520, true),
  ('Rod of Reverberation', 'rare', 3530, true),
  ('Rod of Rulership', 'rare', 3540, true),
  ('Rod of Storms', 'rare', 3550, true),
  ('Rod of the Magicycle', 'rare', 3560, true),
  ('Rod of the Pact Keeper +2', 'rare', 3570, true),
  ('Rod of the Vonindod', 'rare', 3580, true),
  ('Rod of Water Absorption', 'rare', 3590, true),
  ('Rogue''s Mantle', 'rare', 3600, true),
  ('Rope of Entanglement', 'rare', 3610, true),
  ('Ruinous Flail', 'rare', 3620, true),
  ('Sage''s Signet', 'rare', 3630, true),
  ('Saint Markovia''s Thighbone', 'rare', 3640, true),
  ('Salamander Flame Gauntlets', 'rare', 3650, true),
  ('Sanguine Ichor +2', 'rare', 3660, true),
  ('Sash of Sorcerous Synergy', 'rare', 3670, true),
  ('Scaled Ornament (Stirring)', 'rare', 3680, true),
  ('Scarlet Scourge', 'rare', 3690, true),
  ('Scorned Heart Breastplate', 'rare', 3700, true),
  ('Scorpion Armour', 'rare', 3710, true),
  ('Scroll of Nightmares', 'rare', 3720, true),
  ('Scroll of Protection', 'rare', 3730, true),
  ('Scroll of the Jester', 'rare', 3740, true),
  ('Scythe of the Harvest Terror +1', 'rare', 3750, true),
  ('Seraphim''s Stiletto', 'rare', 3760, true),
  ('Serpent''s Fang', 'rare', 3770, true),
  ('Shadow Tag', 'rare', 3780, true),
  ('Shadowfell Brand Tattoo', 'rare', 3790, true),
  ('Shadowfell Shard', 'rare', 3800, true),
  ('Shield +2', 'rare', 3810, true),
  ('Shield of Missile Attraction', 'rare', 3820, true),
  ('Shield of the Justicars', 'rare', 3830, true),
  ('Shrieking Greaves', 'rare', 3840, true),
  ('Siege Staff', 'rare', 3850, true),
  ('Sigil of the Hunt +2', 'rare', 3860, true),
  ('Sky Anchor', 'rare', 3870, true),
  ('Skyglider Shield', 'rare', 3880, true),
  ('Skysail', 'rare', 3890, true),
  ('Soul Pendant', 'rare', 3900, true),
  ('Sovereignseed Satchel', 'rare', 3910, true),
  ('Spell Gem (Bloodstone)', 'rare', 3920, true),
  ('Spell Gem (Quartz)', 'rare', 3930, true),
  ('Spell Scroll (4th Level)', 'rare', 3940, true),
  ('Spell Scroll (5th Level)', 'rare', 3950, true),
  ('Spelljamming Helm', 'rare', 3960, true),
  ('Spellsword', 'rare', 3970, true),
  ('Spellwriter''s Brace', 'rare', 3980, true),
  ('Spellwrought Tattoo (4th Level)', 'rare', 3990, true),
  ('Spellwrought Tattoo (5th Level)', 'rare', 4000, true),
  ('Spider Staff', 'rare', 4010, true),
  ('Spirit Sheath', 'rare', 4020, true),
  ('Spiritwalker Breastplate', 'rare', 4030, true),
  ('Splinterguard', 'rare', 4040, true),
  ('Sream''s Stoppered Oasis', 'rare', 4050, true),
  ('Staff of Charming', 'rare', 4060, true),
  ('Staff of Defense', 'rare', 4070, true),
  ('Staff of Healing', 'rare', 4080, true),
  ('Staff of Swarming Insects', 'rare', 4090, true),
  ('Staff of the Ivory Claw', 'rare', 4100, true),
  ('Staff of the Rooted Hills', 'rare', 4110, true),
  ('Staff of the Woodlands', 'rare', 4120, true),
  ('Staff of Withering', 'rare', 4130, true),
  ('Stalagmight Geode', 'rare', 4140, true),
  ('Starmetal Shard Spear', 'rare', 4150, true),
  ('Starshot Crossbow', 'rare', 4160, true),
  ('Steam Harpoon', 'rare', 4170, true),
  ('Stone of Controlling Earth Elementals', 'rare', 4180, true),
  ('Stonespeaker Crystal', 'rare', 4190, true),
  ('Storm''s Eye Shield', 'rare', 4200, true),
  ('Stormbrewer Bracers', 'rare', 4210, true),
  ('Stormrider Boots', 'rare', 4220, true),
  ('Summer''s Dance', 'rare', 4230, true),
  ('Sun Blade', 'rare', 4240, true),
  ('Sun Staff', 'rare', 4250, true),
  ('Sunforger', 'rare', 4260, true),
  ('Sword of Life Stealing', 'rare', 4270, true),
  ('Sword of Wounding', 'rare', 4280, true),
  ('Teleportation Tablet', 'rare', 4290, true),
  ('Tempest Griffon Bracers', 'rare', 4300, true),
  ('Tentacle Rod', 'rare', 4310, true),
  ('Thalamus Thread', 'rare', 4320, true),
  ('Torrdok''s Magnificent Forgery', 'rare', 4330, true),
  ('Traitor''s Gauntlet', 'rare', 4340, true),
  ('Tremor Spike', 'rare', 4350, true),
  ('Two Birds Sling', 'rare', 4360, true),
  ('Tyrannosaurus Rax', 'rare', 4370, true),
  ('Urnblade', 'rare', 4380, true),
  ('Verax Weapon', 'rare', 4390, true),
  ('Vicious Weapon', 'rare', 4400, true),
  ('Viper Khopesh', 'rare', 4410, true),
  ('Voidwalker Armor', 'rare', 4420, true),
  ('Voyage Collar', 'rare', 4430, true),
  ('Wand of Binding', 'rare', 4440, true),
  ('Wand of Enemy Detection', 'rare', 4450, true),
  ('Wand of Fear', 'rare', 4460, true),
  ('Wand of Fireballs', 'rare', 4470, true),
  ('Wand of Gilding', 'rare', 4480, true),
  ('Wand of Lightning Bolts', 'rare', 4490, true),
  ('Wand of Paralysis', 'rare', 4500, true),
  ('Wand of Stars', 'rare', 4510, true),
  ('Wand of the Frostrose', 'rare', 4520, true),
  ('Wand of the War Mage +2', 'rare', 4530, true),
  ('Wand of Viscid Globs', 'rare', 4540, true),
  ('Wand of Winter', 'rare', 4550, true),
  ('Wand of Wonder', 'rare', 4560, true),
  ('War Horn of Valor', 'rare', 4570, true),
  ('Wardancer''s Spear', 'rare', 4580, true),
  ('Warhammer of Eruptions', 'rare', 4590, true),
  ('Warp Anchor', 'rare', 4600, true),
  ('Warrior''s Passkey', 'rare', 4610, true),
  ('Wavecutter', 'rare', 4620, true),
  ('Wayfarer''s Boots', 'rare', 4630, true),
  ('Wayfinder Sphere', 'rare', 4640, true),
  ('Weapon +2', 'rare', 4650, true),
  ('Weapon of Certain Death', 'rare', 4660, true),
  ('Weapon of the Sun and Moon', 'rare', 4670, true),
  ('Webgrip Bow', 'rare', 4680, true),
  ('Weird Tank', 'rare', 4690, true),
  ('Whirling Weapons', 'rare', 4700, true),
  ('Whisper Jar (Rank 3)', 'rare', 4710, true),
  ('Whisper Jar (Rank 4)', 'rare', 4720, true),
  ('Widow''s Tea', 'rare', 4730, true),
  ('Wildfire Ammunition', 'rare', 4740, true),
  ('Wind Riders', 'rare', 4750, true),
  ('Wind-Up Merchant', 'rare', 4760, true),
  ('Wings of Flying', 'rare', 4770, true),
  ('Wraps of Unarmed Power +2', 'rare', 4780, true),
  ('Wraps Of Unarmed Prowess', 'rare', 4790, true),
  ('Wyrmling Wristlet', 'rare', 4800, true),
  ('Wyrmshide Bow', 'rare', 4810, true),
  ('Xorn-Sole Boots', 'rare', 4820, true),
  ('Zephyr Armor', 'rare', 4830, true),
  ('Abjurer''s Bangle', 'veryrare', 10, true),
  ('Abracadabrus', 'veryrare', 20, true),
  ('Absorbing Tattoo', 'veryrare', 30, true),
  ('Aciurgist''s Blade', 'veryrare', 40, true),
  ('All Purpose Tool +3', 'veryrare', 50, true),
  ('Amethyst Lodestone', 'veryrare', 60, true),
  ('Ammunition +3', 'veryrare', 70, true),
  ('Amulet of the Black Skull', 'veryrare', 80, true),
  ('Amulet of the Devout +3', 'veryrare', 90, true),
  ('Amulet of the Night', 'veryrare', 100, true),
  ('Amulet of the Planes', 'veryrare', 110, true),
  ('Amulet of the Spirit Naga', 'veryrare', 120, true),
  ('Animated Shield', 'veryrare', 130, true),
  ('Anstruth Harp', 'veryrare', 140, true),
  ('Antimagic Armor', 'veryrare', 150, true),
  ('Arborguard Shield', 'veryrare', 160, true),
  ('Arc of the Alicorn', 'veryrare', 170, true),
  ('Arcane Cannon', 'veryrare', 180, true),
  ('Arcane Grimoire +3', 'veryrare', 190, true),
  ('Arcane Propulsion Arm', 'veryrare', 200, true),
  ('Archivist''s Key', 'veryrare', 210, true),
  ('Armor +2', 'veryrare', 220, true),
  ('Armor of Safeguarding', 'veryrare', 230, true),
  ('Arrow of Slaying', 'veryrare', 240, true),
  ('Ashen Katana +3', 'veryrare', 250, true),
  ('Ashen Kunai +3', 'veryrare', 260, true),
  ('Ashen Kusarigama +3', 'veryrare', 270, true),
  ('Ashen Naginata +3', 'veryrare', 280, true),
  ('Ashen Odachi +3', 'veryrare', 290, true),
  ('Ashen Tanegashima +3', 'veryrare', 300, true),
  ('Ashen Yumi +3', 'veryrare', 310, true),
  ('Bag of Devouring', 'veryrare', 320, true),
  ('Baleful Talon', 'veryrare', 330, true),
  ('Barrier Tattoo', 'veryrare', 340, true),
  ('Battle Standard of Infernal Power', 'veryrare', 350, true),
  ('Belt of Giant Strength (Fire Giant)', 'veryrare', 360, true),
  ('Belt of Giant Strength (Frost or Stone Giant)', 'veryrare', 370, true),
  ('Blade of the Medusa', 'veryrare', 380, true),
  ('Blast Scepter', 'veryrare', 390, true),
  ('Bloodaxe', 'veryrare', 400, true),
  ('Bloodseeker Ammunition', 'veryrare', 410, true),
  ('Bloodshed Blade', 'veryrare', 420, true),
  ('Bloodthirster Scimitar', 'veryrare', 430, true),
  ('Bloodwell Vial +3', 'veryrare', 440, true),
  ('Bloody Marilith (Very Rare)', 'veryrare', 450, true),
  ('Boots of Haste', 'veryrare', 460, true),
  ('Bow of Melodies', 'veryrare', 470, true),
  ('Bow of the Spelldrinker', 'veryrare', 480, true),
  ('Bracelet of Rock Magic', 'veryrare', 490, true),
  ('Bulette Torpedo', 'veryrare', 500, true),
  ('Camilla''s Quicksilver Mirror', 'veryrare', 510, true),
  ('Candle of Invocation', 'veryrare', 520, true),
  ('Carpet of Flying', 'veryrare', 530, true),
  ('Carrion Shroud', 'veryrare', 540, true),
  ('Cataclysm Bolts', 'veryrare', 550, true),
  ('Cauldron of Rebirth', 'veryrare', 560, true),
  ('Charged Rapier', 'veryrare', 570, true),
  ('Chronal Sphere', 'veryrare', 580, true),
  ('Chronolometer', 'veryrare', 590, true),
  ('Chronomancer''s Eyepiece', 'veryrare', 600, true),
  ('Circlet of the Sharpened Mind', 'veryrare', 610, true),
  ('Cloak of Arachnida', 'veryrare', 620, true),
  ('Cloche of Surprise Treats', 'veryrare', 630, true),
  ('Clockwork Armor', 'veryrare', 640, true),
  ('Conch of Teleportation', 'veryrare', 650, true),
  ('Corecut Dagger', 'veryrare', 660, true),
  ('Crown Of Whirling Comets', 'veryrare', 670, true),
  ('Crystal Ball', 'veryrare', 680, true),
  ('Crystalline Chronicle', 'veryrare', 690, true),
  ('Dancing Sword', 'veryrare', 700, true),
  ('Deathly Diadem', 'veryrare', 710, true),
  ('Deck Of Dimensions', 'veryrare', 720, true),
  ('Deck Of Wild Cards', 'veryrare', 730, true),
  ('Demon Armor', 'veryrare', 740, true),
  ('Diabolic Conduit +3', 'veryrare', 750, true),
  ('Dimensional Loop', 'veryrare', 760, true),
  ('Dispelling Stone', 'veryrare', 770, true),
  ('Dragon Horn Pauldron', 'veryrare', 780, true),
  ('Dragon Scale Mail', 'veryrare', 790, true),
  ('Dragon Turtle Barding', 'veryrare', 800, true),
  ('Dragon Vessel (Wakened)', 'veryrare', 810, true),
  ('Dragon''s Wrath (Wakened)', 'veryrare', 820, true),
  ('Dragon-Touched Focus (Wakened)', 'veryrare', 830, true),
  ('Dragonhide Belt +3', 'veryrare', 840, true),
  ('Dusk Dagger', 'veryrare', 850, true),
  ('Duskcrusher', 'veryrare', 860, true),
  ('Dwarven Plate', 'veryrare', 870, true),
  ('Dwarven Thrower', 'veryrare', 880, true),
  ('Dyrrn''s Tentacle Whip', 'veryrare', 890, true),
  ('Efreeti Bottle', 'veryrare', 900, true),
  ('Elementalist''s Staff', 'veryrare', 910, true),
  ('Enspelled Armor(4th lvl spell)', 'veryrare', 920, true),
  ('Enspelled Armor(5th lvl spell)', 'veryrare', 930, true),
  ('Enspelled Staff(4th lvl spell)', 'veryrare', 940, true),
  ('Enspelled Staff(5th lvl spell)', 'veryrare', 950, true),
  ('Enspelled Weapon(4th lvl spell)', 'veryrare', 960, true),
  ('Enspelled Weapon(5th lvl spell)', 'veryrare', 970, true),
  ('Enzymatic Gastrostaff', 'veryrare', 980, true),
  ('Far Gear', 'veryrare', 990, true),
  ('Fate Cutter Shears', 'veryrare', 1000, true),
  ('Fate Dealer''s Deck', 'veryrare', 1010, true),
  ('Figurine of Wondrous Power (Obsidian Steed)', 'veryrare', 1020, true),
  ('Fish Suit', 'veryrare', 1030, true),
  ('Fool''s Blade', 'veryrare', 1040, true),
  ('Fool''s Lamp', 'veryrare', 1050, true),
  ('Forcebreaker Weapon', 'veryrare', 1060, true),
  ('Frost Brand', 'veryrare', 1070, true),
  ('Frostburn Spear', 'veryrare', 1080, true),
  ('Furious Flail', 'veryrare', 1090, true),
  ('Gateway Ring', 'veryrare', 1100, true),
  ('Ghost Step Tattoo', 'veryrare', 1110, true),
  ('Gloves of Mimicry', 'veryrare', 1120, true),
  ('Gnomengarde Grenade', 'veryrare', 1130, true),
  ('Grasping Staff', 'veryrare', 1140, true),
  ('Green Knight''s Vow', 'veryrare', 1150, true),
  ('Guild Keyrune (Dimir)', 'veryrare', 1160, true),
  ('Guild Keyrune (Golgari)', 'veryrare', 1170, true),
  ('Halberd of the Reforged Soul +3', 'veryrare', 1180, true),
  ('Hammer of Runic Focus', 'veryrare', 1190, true),
  ('Heartless Cage Pendant', 'veryrare', 1200, true),
  ('Helm of Brilliance', 'veryrare', 1210, true),
  ('Helm of Devil Command', 'veryrare', 1220, true),
  ('Helm of the Broken Dragon', 'veryrare', 1230, true),
  ('Helm of the Chromatic Dragon', 'veryrare', 1240, true),
  ('Helm of the Platinum Dragon', 'veryrare', 1250, true),
  ('Helm of the Ruby Dragon', 'veryrare', 1260, true),
  ('Heward''s Hireling Armor', 'veryrare', 1270, true),
  ('Hoarder''s Haul (Very Rare)', 'veryrare', 1280, true),
  ('Horn of the Wild Hunt', 'veryrare', 1290, true),
  ('Horn of Valhalla (Bronze)', 'veryrare', 1300, true),
  ('Horned Ring', 'veryrare', 1310, true),
  ('Horseshoes of a Zephyr', 'veryrare', 1320, true),
  ('Hour and Minute', 'veryrare', 1330, true),
  ('Hourglass of Slumber', 'veryrare', 1340, true),
  ('Hunter''s Coat', 'veryrare', 1350, true),
  ('Hydra Charm', 'veryrare', 1360, true),
  ('Illusionist''s Bracers', 'veryrare', 1370, true),
  ('Impact Plate', 'veryrare', 1380, true),
  ('Infernal Chain', 'veryrare', 1390, true),
  ('Ingot of the Skold Rune', 'veryrare', 1400, true),
  ('Instrument of Roses and Thorns', 'veryrare', 1410, true),
  ('Ioun Stone (Absorption)', 'veryrare', 1420, true),
  ('Ioun Stone (Agility)', 'veryrare', 1430, true),
  ('Ioun Stone (Fortitude)', 'veryrare', 1440, true),
  ('Ioun Stone (Insight)', 'veryrare', 1450, true),
  ('Ioun Stone (Intellect)', 'veryrare', 1460, true),
  ('Ioun Stone (Leadership)', 'veryrare', 1470, true),
  ('Ioun Stone (Strength)', 'veryrare', 1480, true),
  ('Ioun Stone (Vitality)', 'veryrare', 1490, true),
  ('Javelin of Backbiting', 'veryrare', 1500, true),
  ('Ki Blade', 'veryrare', 1510, true),
  ('Kraken Band', 'veryrare', 1520, true),
  ('Kyrzin''s Ooze', 'veryrare', 1530, true),
  ('Lady Phantasma''s Material Anchor', 'veryrare', 1540, true),
  ('Last Stand Armor', 'veryrare', 1550, true),
  ('Lifewell Tattoo', 'veryrare', 1560, true),
  ('Living Armor', 'veryrare', 1570, true),
  ('Living Loot Satchel (Rank 4)', 'veryrare', 1580, true),
  ('Lord’s Ensemble', 'veryrare', 1590, true),
  ('Lucent Destroyer', 'veryrare', 1600, true),
  ('Magentan Sun-Saw (Very Rare)', 'veryrare', 1610, true),
  ('Manual of Bodily Health', 'veryrare', 1620, true),
  ('Manual of Gainful Exercise', 'veryrare', 1630, true),
  ('Manual of Golems', 'veryrare', 1640, true),
  ('Manual of Quickness of Action', 'veryrare', 1650, true),
  ('Masks of the Sacred Beasts (Mule)', 'veryrare', 1660, true),
  ('Matron''s Mug', 'veryrare', 1670, true),
  ('Mindmaster''s Monocle', 'veryrare', 1680, true),
  ('Mirror of Infinite Transpondence', 'veryrare', 1690, true),
  ('Mirror of Life Trapping', 'veryrare', 1700, true),
  ('Mistral Mantle', 'veryrare', 1710, true),
  ('Moon Sickle +3', 'veryrare', 1720, true),
  ('Mourningsteel Demi-Gauntlets', 'veryrare', 1730, true),
  ('Navigation Orb', 'veryrare', 1740, true),
  ('Nimbus Coronet', 'veryrare', 1750, true),
  ('Nine Lives Stealer', 'veryrare', 1760, true),
  ('Nolzur’s Marvelous Pigments', 'veryrare', 1770, true),
  ('Novanite Armor', 'veryrare', 1780, true),
  ('Oathbow', 'veryrare', 1790, true),
  ('Oathkeeper''s Resolve', 'veryrare', 1800, true),
  ('Ogramau''s Graveyard', 'veryrare', 1810, true),
  ('Oil of Sharpness', 'veryrare', 1820, true),
  ('Orb of the Veil', 'veryrare', 1830, true),
  ('Orostead Iced Tea (Very Rare)', 'veryrare', 1840, true),
  ('Pennant of the Vind Rune', 'veryrare', 1850, true),
  ('Peregrine Mask', 'veryrare', 1860, true),
  ('Phasing Bow', 'veryrare', 1870, true),
  ('Phoenix Breastplate', 'veryrare', 1880, true),
  ('Phoenix Rocket Sword', 'veryrare', 1890, true),
  ('Polymorph Blade', 'veryrare', 1900, true),
  ('Potion of Flying', 'veryrare', 1910, true),
  ('Potion of Giant Strength (Cloud Giant)', 'veryrare', 1920, true),
  ('Potion of Greater Invisibility', 'veryrare', 1930, true),
  ('Potion of Healing (Supreme)', 'veryrare', 1940, true),
  ('Potion of Longevity', 'veryrare', 1950, true),
  ('Potion of Mind Control (Monster)', 'veryrare', 1960, true),
  ('Potion of Possibility', 'veryrare', 1970, true),
  ('Potion of Speed', 'veryrare', 1980, true),
  ('Potion of Vitality', 'veryrare', 1990, true),
  ('Prehistoric Figurines of Wondrous Power', 'veryrare', 2000, true),
  ('Radiant War Pick', 'veryrare', 2010, true),
  ('Raven''s Slumber', 'veryrare', 2020, true),
  ('Reincarnation Dust', 'veryrare', 2030, true),
  ('Rejuvenating Draft (Very Rare)', 'veryrare', 2040, true),
  ('Reliquary of Holy Memories', 'veryrare', 2050, true),
  ('Rhythm-Maker''s Drum +3', 'veryrare', 2060, true),
  ('Ring of Amity', 'veryrare', 2070, true),
  ('Ring of Lunar Might', 'veryrare', 2080, true),
  ('Ring of Red Fury', 'veryrare', 2090, true),
  ('Ring of Regeneration', 'veryrare', 2100, true),
  ('Ring of Shooting Stars', 'veryrare', 2110, true),
  ('Ring of Telekinesis', 'veryrare', 2120, true),
  ('Ring of the Split Mind', 'veryrare', 2130, true),
  ('Robe of Scintillating Colors', 'veryrare', 2140, true),
  ('Robe of Stars', 'veryrare', 2150, true),
  ('Rod of Absorption', 'veryrare', 2160, true),
  ('Rod of Alertness', 'veryrare', 2170, true),
  ('Rod of Hellish Flames', 'veryrare', 2180, true),
  ('Rod of Security', 'veryrare', 2190, true),
  ('Rod of the Pact Keeper +3', 'veryrare', 2200, true),
  ('Rotor of Return', 'veryrare', 2210, true),
  ('Royal Blade of Amphibios', 'veryrare', 2220, true),
  ('Ruidium Armor', 'veryrare', 2230, true),
  ('Ruidium Shield', 'veryrare', 2240, true),
  ('Ruidium Weapon', 'veryrare', 2250, true),
  ('Sage''s Signet', 'veryrare', 2260, true),
  ('Sanctum Amulet', 'veryrare', 2270, true),
  ('Sanguine Ichor +3', 'veryrare', 2280, true),
  ('Sapphire Buckler', 'veryrare', 2290, true),
  ('Scaled Ornament (Wakened)', 'veryrare', 2300, true),
  ('Scepter of Faith', 'veryrare', 2310, true),
  ('Scimitar of Speed', 'veryrare', 2320, true),
  ('Scroll of Mapping (Very Rare)', 'veryrare', 2330, true),
  ('Shard of the Ise Rune', 'veryrare', 2340, true),
  ('Shield +3', 'veryrare', 2350, true),
  ('Shield of the Uven Rune', 'veryrare', 2360, true),
  ('Shooting Star', 'veryrare', 2370, true),
  ('Sigil of the Hunt +3', 'veryrare', 2380, true),
  ('Skull Helm', 'veryrare', 2390, true),
  ('Sling Bullets of Althemone', 'veryrare', 2400, true),
  ('Spear of Backbiting', 'veryrare', 2410, true),
  ('Spell Gem (Amber)', 'veryrare', 2420, true),
  ('Spell Gem (Jade)', 'veryrare', 2430, true),
  ('Spell Gem (Topaz)', 'veryrare', 2440, true),
  ('Spell Scroll (6th Level)', 'veryrare', 2450, true),
  ('Spell Scroll (7th Level)', 'veryrare', 2460, true),
  ('Spell Scroll (8th Level)', 'veryrare', 2470, true),
  ('Spellguard Shield', 'veryrare', 2480, true),
  ('Staff of Dunamancy', 'veryrare', 2490, true),
  ('Staff of Fate', 'veryrare', 2500, true),
  ('Staff of Fire', 'veryrare', 2510, true),
  ('Staff of Frost', 'veryrare', 2520, true),
  ('Staff of Power', 'veryrare', 2530, true),
  ('Staff of Striking', 'veryrare', 2540, true),
  ('Staff of Thunder and Lightning', 'veryrare', 2550, true),
  ('Starmetal Sliver', 'veryrare', 2560, true),
  ('Stonemaker War Pick', 'veryrare', 2570, true),
  ('Sword of Paruns', 'veryrare', 2580, true),
  ('Sword of Sharpness', 'veryrare', 2590, true),
  ('Thunderbuss', 'veryrare', 2600, true),
  ('Tidecaller Trident', 'veryrare', 2610, true),
  ('Timepiece of Travel', 'veryrare', 2620, true),
  ('Tinkertop Boltblaster 1000', 'veryrare', 2630, true),
  ('Titan''s Tooth Claymore', 'veryrare', 2640, true),
  ('Tome of Advanced Fighting Styles', 'veryrare', 2650, true),
  ('Tome of Clear Thought', 'veryrare', 2660, true),
  ('Tome of Leadership and influence', 'veryrare', 2670, true),
  ('Tome of Understanding', 'veryrare', 2680, true),
  ('Ventilating Lungs', 'veryrare', 2690, true),
  ('Voyager Staff', 'veryrare', 2700, true),
  ('Vyra''s Broken Path', 'veryrare', 2710, true),
  ('Wand of Merriment', 'veryrare', 2720, true),
  ('Wand of Necrosis', 'veryrare', 2730, true),
  ('Wand of Polymorph', 'veryrare', 2740, true),
  ('Wand of Puppetry', 'veryrare', 2750, true),
  ('Wand of the War Mage +3', 'veryrare', 2760, true),
  ('War''s Wager', 'veryrare', 2770, true),
  ('Warding Staff', 'veryrare', 2780, true),
  ('Watchful Helm', 'veryrare', 2790, true),
  ('Weapon +3', 'veryrare', 2800, true),
  ('Weapon of Throne''s Command', 'veryrare', 2810, true),
  ('Wheel of Stars', 'veryrare', 2820, true),
  ('Wind and Whirl', 'veryrare', 2830, true),
  ('Wraps of the Restless', 'veryrare', 2840, true),
  ('Wraps of Unarmed Power +3', 'veryrare', 2850, true),
  ('Wyrmreaver Gauntlets', 'veryrare', 2860, true),
  ('Xibalban Blade', 'veryrare', 2870, true),
  ('Yellow Harbinger''s Path', 'veryrare', 2880, true),
  ('Adze of Annam', 'legendary', 10, true),
  ('Agony', 'legendary', 20, true),
  ('Akmon, Hammer of Purphoros', 'legendary', 30, true),
  ('Ao Hai''s Fang', 'legendary', 40, true),
  ('Apparatus of Kwalish', 'legendary', 50, true),
  ('Arista, Wand of the Spire', 'legendary', 60, true),
  ('Armor +3', 'legendary', 70, true),
  ('Armor of Invulnerability', 'legendary', 80, true),
  ('Armor of the Valiant Soul', 'legendary', 90, true),
  ('Ashrender, Odachi of the Ashen Veil', 'legendary', 100, true),
  ('Axe of the Dwarvish Lords', 'legendary', 110, true),
  ('Azuredge', 'legendary', 120, true),
  ('Baba Yaga’s Mortar and Pestle', 'legendary', 130, true),
  ('Belashyrra''s Beholder Crown', 'legendary', 140, true),
  ('Belt of Giant Strength (Cloud Giant)', 'legendary', 150, true),
  ('Belt of Giant Strength (Storm Giant)', 'legendary', 160, true),
  ('Bigby''s Beneficent Bracelet', 'legendary', 170, true),
  ('Black Crystal Tablet', 'legendary', 180, true),
  ('Black Dragon Mask', 'legendary', 190, true),
  ('Blackrazor', 'legendary', 200, true),
  ('Blackstaff', 'legendary', 210, true),
  ('Blade of Avernus', 'legendary', 220, true),
  ('Blade of Broken Mirrors', 'legendary', 230, true),
  ('Blade of the Fading Veil, Katana of the Ashen Veil', 'legendary', 240, true),
  ('Blood Fury Tattoo', 'legendary', 250, true),
  ('Bloodmire Soulflame Lantern', 'legendary', 260, true),
  ('Blue Dragon Mask', 'legendary', 270, true),
  ('Book of Exalted Deeds', 'legendary', 280, true),
  ('Book of Vile Darkness', 'legendary', 290, true),
  ('Bookmark', 'legendary', 300, true),
  ('Cabal''s Ruin', 'legendary', 310, true),
  ('Circlet of Barbed Vision', 'legendary', 320, true),
  ('Cloak of Invisibility', 'legendary', 330, true),
  ('Condemner', 'legendary', 340, true),
  ('Crescent of Ash, Naginata of the Ashen Veil', 'legendary', 350, true),
  ('Crook of Rao', 'legendary', 360, true),
  ('Crown of Storms', 'legendary', 370, true),
  ('Crystal Ball (various)', 'legendary', 380, true),
  ('Cubic Gate', 'legendary', 390, true),
  ('Danoth''s Visor', 'legendary', 400, true),
  ('Davy Jones''s Key', 'legendary', 410, true),
  ('Dawnbringer', 'legendary', 420, true),
  ('Death''s Shadow', 'legendary', 430, true),
  ('Deathwalker''s Ward', 'legendary', 440, true),
  ('Defender', 'legendary', 450, true),
  ('Dekella, Bident of Thassa', 'legendary', 460, true),
  ('Demonomicon of Iggwilv', 'legendary', 470, true),
  ('Dimensional Loop', 'legendary', 480, true),
  ('Dimensional Seal', 'legendary', 490, true),
  ('Draakhorn', 'legendary', 500, true),
  ('Dragon Vessel (Ascendant)', 'legendary', 510, true),
  ('Dragon''s Wrath (Ascendant)', 'legendary', 520, true),
  ('Dragon-Touched Focus (Ascendant)', 'legendary', 530, true),
  ('Dragonlance', 'legendary', 540, true),
  ('Dragonstaff of Ahghairon', 'legendary', 550, true),
  ('Drown', 'legendary', 560, true),
  ('Efreeti Chain', 'legendary', 570, true),
  ('Endless Current', 'legendary', 580, true),
  ('Enspelled Armor(6th lvl spell)', 'legendary', 590, true),
  ('Enspelled Armor(7th lvl spell)', 'legendary', 600, true),
  ('Enspelled Armor(8th lvl spell)', 'legendary', 610, true),
  ('Enspelled Staff(6th lvl spell)', 'legendary', 620, true),
  ('Enspelled Staff(7th lvl spell)', 'legendary', 630, true),
  ('Enspelled Staff(8th lvl spell)', 'legendary', 640, true),
  ('Enspelled Weapon(6th lvl spell)', 'legendary', 650, true),
  ('Enspelled Weapon(7th lvl spell)', 'legendary', 660, true),
  ('Enspelled Weapon(8th lvl spell)', 'legendary', 670, true),
  ('Ephixis, Bow of Nylea', 'legendary', 680, true),
  ('Erevale''s Final Mercy', 'legendary', 690, true),
  ('Erevale''s Shroud', 'legendary', 700, true),
  ('Erevale''s Vestment', 'legendary', 710, true),
  ('Eternal Slayer', 'legendary', 720, true),
  ('Euryale''s Aegis', 'legendary', 730, true),
  ('Eye and Hand of Vecna', 'legendary', 740, true),
  ('Fane-Eater', 'legendary', 750, true),
  ('Fate Dealer''s Deck', 'legendary', 760, true),
  ('Fell-Rider Chariot', 'legendary', 770, true),
  ('Fenthras', 'legendary', 780, true),
  ('Figurine of Wondrous Power (Gold Canary)', 'legendary', 790, true),
  ('Flail of Tiamat', 'legendary', 800, true),
  ('Gaze of the Veil Tanegashima of the Ashen Veil', 'legendary', 810, true),
  ('Gladius of the Everfighter', 'legendary', 820, true),
  ('Glaive of the Revenant King', 'legendary', 830, true),
  ('Gloves of Soul Catching', 'legendary', 840, true),
  ('Godsteel Warplate', 'legendary', 850, true),
  ('Godsteel Worldcarver', 'legendary', 860, true),
  ('Gorget of the Holy Soldier', 'legendary', 870, true),
  ('Graz''tchar, the Decadent End', 'legendary', 880, true),
  ('Greater Silver Sword', 'legendary', 890, true),
  ('Green Dragon Mask', 'legendary', 900, true),
  ('Grimoire Infinitus', 'legendary', 910, true),
  ('Grovelthrash', 'legendary', 920, true),
  ('Guardian''s Reliquary', 'legendary', 930, true),
  ('Gurt’s Greataxe', 'legendary', 940, true),
  ('H''rethi Soul Scepter', 'legendary', 950, true),
  ('Half Plate of the Blind Martyr', 'legendary', 960, true),
  ('Hammer of Thunderbolts', 'legendary', 970, true),
  ('Harp of Gilded Plenty', 'legendary', 980, true),
  ('Hatred, the Wrathful Edge', 'legendary', 990, true),
  ('Hazirawn', 'legendary', 1000, true),
  ('Heart of Damned Intervention', 'legendary', 1010, true),
  ('Heaven''s Edge', 'legendary', 1020, true),
  ('Heaven''s Gavel', 'legendary', 1030, true),
  ('Helm of Disjunction', 'legendary', 1040, true),
  ('Helm of Perfect Potential', 'legendary', 1050, true),
  ('Helm of the Justicars', 'legendary', 1060, true),
  ('Helm of the Scavenger', 'legendary', 1070, true),
  ('Hide of the Feral Guardian', 'legendary', 1080, true),
  ('Hither-Thither Staff', 'legendary', 1090, true),
  ('Holy Avenger', 'legendary', 1100, true),
  ('Honor''s Last Stand', 'legendary', 1110, true),
  ('Horn of Beckoning Death', 'legendary', 1120, true),
  ('Horn of Valhalla (iron)', 'legendary', 1130, true),
  ('Icon of Ravenloft', 'legendary', 1140, true),
  ('Indigo Stray''s Conviction', 'legendary', 1150, true),
  ('Infernal Tack', 'legendary', 1160, true),
  ('Infiltrator''s Key', 'legendary', 1170, true),
  ('Ioun Stone (Greater Absorption)', 'legendary', 1180, true),
  ('Ioun Stone (Mastery)', 'legendary', 1190, true),
  ('Ioun Stone (Regeneration)', 'legendary', 1200, true),
  ('Iron Fang', 'legendary', 1210, true),
  ('Iron Flask', 'legendary', 1220, true),
  ('Jester''s Mask', 'legendary', 1230, true),
  ('Jewel of Three Prayers', 'legendary', 1240, true),
  ('Khrusor, Spear of Heliod', 'legendary', 1250, true),
  ('Kiss of the Changebringer', 'legendary', 1260, true),
  ('Korolnor Scepter', 'legendary', 1270, true),
  ('Lash of Shadows', 'legendary', 1280, true),
  ('Life Turner', 'legendary', 1290, true),
  ('Lightseer''s Gaze', 'legendary', 1300, true),
  ('Longbow of the Healing Hearth', 'legendary', 1310, true),
  ('Lost Crown of Besilmer', 'legendary', 1320, true),
  ('Luba’s Tarokka of Souls', 'legendary', 1330, true),
  ('Luck Blade (with Wishes)', 'legendary', 1340, true),
  ('Luck Blade (without Wishes)', 'legendary', 1350, true),
  ('Luxon Beacon', 'legendary', 1360, true),
  ('Mabaran Resonator', 'legendary', 1370, true),
  ('Mace of the Black Crown', 'legendary', 1380, true),
  ('Mage Eater Scythe', 'legendary', 1390, true),
  ('Mask of the Dragon Queen', 'legendary', 1400, true),
  ('Masks of the Sacred Beasts (Jackal)', 'legendary', 1410, true),
  ('Master''s Call', 'legendary', 1420, true),
  ('Mastix, Whip of Erebos', 'legendary', 1430, true),
  ('Matalotok', 'legendary', 1440, true),
  ('Meta Mantle', 'legendary', 1450, true),
  ('Mighty Servant of Leuk-o', 'legendary', 1460, true),
  ('Moonblade', 'legendary', 1470, true),
  ('Morath, Scepter of the Soul Vortex', 'legendary', 1480, true),
  ('Mourningsteel Half Plate', 'legendary', 1490, true),
  ('Murxagor''s Orb', 'legendary', 1500, true),
  ('Mythcarver', 'legendary', 1510, true),
  ('Nether Scroll of Azumar', 'legendary', 1520, true),
  ('Nightfall Pearl', 'legendary', 1530, true),
  ('Nimbus, First Staff of the Thunderbirds', 'legendary', 1540, true),
  ('Obsidian Flint Dragon Plate', 'legendary', 1550, true),
  ('Octavius''s Saber', 'legendary', 1560, true),
  ('Ollamh Harp', 'legendary', 1570, true),
  ('Orb of Dragonkind', 'legendary', 1580, true),
  ('Orb of Skoraeus', 'legendary', 1590, true),
  ('Orcsplitter', 'legendary', 1600, true),
  ('Plate Armor of Etherealness', 'legendary', 1610, true),
  ('Plate of the Dawnmartyr', 'legendary', 1620, true),
  ('Platinum Scarf', 'legendary', 1630, true),
  ('Potion of Dragon''s Majesty', 'legendary', 1640, true),
  ('Potion of Giant Size', 'legendary', 1650, true),
  ('Potion of Giant Strength (Storm Giant)', 'legendary', 1660, true),
  ('Powered Armor', 'legendary', 1670, true),
  ('Prehistoric Figurines of Wondrous Power', 'legendary', 1680, true),
  ('Pyremaul', 'legendary', 1690, true),
  ('Pyxis of Pandemonium', 'legendary', 1700, true),
  ('Quiver of Elemental Chaos', 'legendary', 1710, true),
  ('Rakdos Riteknife', 'legendary', 1720, true),
  ('Realmswarden Greataxe', 'legendary', 1730, true),
  ('Reaper''s Scream', 'legendary', 1740, true),
  ('Red Dragon Mask', 'legendary', 1750, true),
  ('Red Queen''s Burden', 'legendary', 1760, true),
  ('Red Wizard Blade', 'legendary', 1770, true),
  ('Rejuvenating Draft (Legendary)', 'legendary', 1780, true),
  ('Reliquary of Holy Memories', 'legendary', 1790, true),
  ('Relithia''s Grace', 'legendary', 1800, true),
  ('Relithia''s Justice', 'legendary', 1810, true),
  ('Relithia''s Stride', 'legendary', 1820, true),
  ('Ring of Djinni Summoning', 'legendary', 1830, true),
  ('Ring of Elemental Command', 'legendary', 1840, true),
  ('Ring of Invisibility', 'legendary', 1850, true),
  ('Ring of Spell Turning', 'legendary', 1860, true),
  ('Ring of the Assassin Lord', 'legendary', 1870, true),
  ('Ring of Three Wishes', 'legendary', 1880, true),
  ('Ring of Winter', 'legendary', 1890, true),
  ('Robe of the Archmagi', 'legendary', 1900, true),
  ('Rod of Lordly Might', 'legendary', 1910, true),
  ('Rod of Resurrection', 'legendary', 1920, true),
  ('Royal Incinerator', 'legendary', 1930, true),
  ('Ruby Weave Gem', 'legendary', 1940, true),
  ('Ruin''s Wake', 'legendary', 1950, true),
  ('Ruinblade', 'legendary', 1960, true),
  ('Scaled Ornament(ascendant)', 'legendary', 1970, true),
  ('Scarab of Protection', 'legendary', 1980, true),
  ('Scroll of Tarrasque Summoning', 'legendary', 1990, true),
  ('Scroll of the Comet', 'legendary', 2000, true),
  ('Shadowcoil, Kusarigama of the Ashen Veil', 'legendary', 2010, true),
  ('Shadowscale Shroud', 'legendary', 2020, true),
  ('Shadowsight, Yumi of the Ashen Veil', 'legendary', 2030, true),
  ('Shield of the Blazing Dreadnought', 'legendary', 2040, true),
  ('Shield of the Hidden Lord', 'legendary', 2050, true),
  ('Silken Spite', 'legendary', 2060, true),
  ('Silverwind, the Cleansing Breeze', 'legendary', 2070, true),
  ('Skylit Greaves', 'legendary', 2080, true),
  ('Slaying Longbow', 'legendary', 2090, true),
  ('Soul-Searing Scythe', 'legendary', 2100, true),
  ('Sovereign Glue', 'legendary', 2110, true),
  ('Spell Bottle', 'legendary', 2120, true),
  ('Spell Gem (Diamond)', 'legendary', 2130, true),
  ('Spell Gem (Ruby)', 'legendary', 2140, true),
  ('Spell Gem (Star Ruby)', 'legendary', 2150, true),
  ('Spell Scroll (9th Level)', 'legendary', 2160, true),
  ('Spellfire Bow', 'legendary', 2170, true),
  ('Sphere of Annihilation', 'legendary', 2180, true),
  ('Spindle Of Fate', 'legendary', 2190, true),
  ('Spire of Conflux', 'legendary', 2200, true),
  ('Spirit Cleaver', 'legendary', 2210, true),
  ('Staff of the Forgotten One', 'legendary', 2220, true),
  ('Staff of the Magi', 'legendary', 2230, true),
  ('Star Razor', 'legendary', 2240, true),
  ('Starmetal Nova Armor', 'legendary', 2250, true),
  ('Stone of Golorr', 'legendary', 2260, true),
  ('Stonebreaker''s Breastplate', 'legendary', 2270, true),
  ('Storm Spire', 'legendary', 2280, true),
  ('Stormgirdle', 'legendary', 2290, true),
  ('Sun Sword', 'legendary', 2300, true),
  ('Sword of Answering', 'legendary', 2310, true),
  ('Sword of Kas', 'legendary', 2320, true),
  ('Sword of the Planes', 'legendary', 2330, true),
  ('Sword of Zariel', 'legendary', 2340, true),
  ('Tablet of Reawakening', 'legendary', 2350, true),
  ('Talisman of Pure Good', 'legendary', 2360, true),
  ('Talisman of the Sphere', 'legendary', 2370, true),
  ('Talisman of Ultimate Evil', 'legendary', 2380, true),
  ('Tarrasque Plate', 'legendary', 2390, true),
  ('Teeth of Dahlver-Nar', 'legendary', 2400, true),
  ('Telescopic Transporter', 'legendary', 2410, true),
  ('The Bloody End', 'legendary', 2420, true),
  ('The Griffon’s Saddlebag', 'legendary', 2430, true),
  ('The Infernal Machine of Lum the Mad', 'legendary', 2440, true),
  ('Tinderstrike', 'legendary', 2450, true),
  ('Titanstone Knuckles', 'legendary', 2460, true),
  ('Tome of Lost Knowledge', 'legendary', 2470, true),
  ('Tome of the Stilled Tongue', 'legendary', 2480, true),
  ('Topaz Annihilator', 'legendary', 2490, true),
  ('Underworld Asphodel Regalia', 'legendary', 2500, true),
  ('Universal Solvent', 'legendary', 2510, true),
  ('Veilpiercer, Kunai of the Ashen Veil', 'legendary', 2520, true),
  ('Verminshroud', 'legendary', 2530, true),
  ('Violet King''s Promise', 'legendary', 2540, true),
  ('Vorpal Sword', 'legendary', 2550, true),
  ('Wand of Orcus', 'legendary', 2560, true),
  ('Wand of the Alicorn', 'legendary', 2570, true),
  ('Wave', 'legendary', 2580, true),
  ('Waythe', 'legendary', 2590, true),
  ('Whelm', 'legendary', 2600, true),
  ('Whisper', 'legendary', 2610, true),
  ('White Dragon Mask', 'legendary', 2620, true),
  ('Will of the Talon', 'legendary', 2630, true),
  ('Windvane', 'legendary', 2640, true),
  ('Wraps of Dyamak', 'legendary', 2650, true),
  ('Wreath of the Prism', 'legendary', 2660, true),
  ('Wyrmskull Throne', 'legendary', 2670, true),
  ('Ythryn Mythallar', 'legendary', 2680, true)
ON CONFLICT (name, rarity) DO UPDATE
SET
  sort_order = EXCLUDED.sort_order,
  is_published = EXCLUDED.is_published,
  updated_at = NOW();