INSERT INTO side_quest_objectives (
  guild_id,
  title,
  description,
  sort_order,
  is_published
)
SELECT
  g.id,
  v.title,
  v.description,
  v.sort_order,
  true
FROM guilds g
JOIN (
  VALUES
    ('golden-quill','Flavour Flair','Before initiative is joined on a quest, use your highest level spell slot to do anything that is not a prebuff.',10),
    ('golden-quill','Weave-r Happy','Have the first spell you cast during the quest use your highest available spell slot.',20),
    ('golden-quill','Write It Down Anyway','Return with a written record of the quest, made by you.',30),
    ('golden-quill','Test the Claim','Take a piece of information the party was given and verify or disprove it firsthand.',40),
    ('golden-quill','Recovered Text','Bring writing of any kind from the quest site back to the quest giver.',50),
    ('golden-quill','The Method Matters','Successfully use a spell, item, or technique in a way it was not designed for.',60),
    ('golden-quill','Wrong Turn','Investigate something clearly irrelevant to the quest objective.',70),
    ('golden-quill','Arcane Might Displayed','Enter a single initiative with all of your highest level spell slots available, and end that initiative having spent all of them.',80),
    ('golden-quill','Arcane Might Unwithstood','Have an enemy fail a saving throw against one of your spells.',90),
    ('golden-quill','Arcane Might Unerring','During at least 2 different turns, hit at enemy with a spell attack.',100),
    ('golden-quill','Read the Weave','Identify a magical effect, enchantment, or spell at that you found at the quest site.',110),

    ('iron-vanguard','Claim the Ground','Hold the place where a significant enemy falls until 1 minute after the end of combat.',10),
    ('iron-vanguard','Break the Chain of Command','Personally kill or capture the enemy leader before any other enemy in that encounter dies.',20),
    ('iron-vanguard','Not One Lost','Ensure no party member is reduced to 0 Hit Points.',30),
    ('iron-vanguard','Hold the Line','Never end your turn more than 15 feet from another party member.',40),
    ('iron-vanguard','The Standard Stands','At the start of the quest, you attach a banner to a party member. Ensure that the party member with the banner doesnt fall to 0 HP for the duration of the quest.',50),
    ('iron-vanguard','Spare the Innocent','Do not personally harm any enemy who did not attack first.',60),
    ('iron-vanguard','Kill the Guilty','Personally deliver the killing blow to at least one enemy that attacked first.',70),
    ('iron-vanguard','Fair Fight','Kill an enemy from full HP without any other party member doing damage to it.',80),
    ('iron-vanguard','Draw Their Ire','At least once during the quest, end your turn in a position, where you are the party member that is closest to all enemies.',90),
    ('iron-vanguard','Thick of the Fight','Ending at least 5 of your turn within 5ft to an enemy. Ending your turn within 5ft of more than one enemy counts as ending your turn next to a enemy a number of times equal to the number of enemies within 5ft of you.',100),
    ('iron-vanguard','Against the Unclean','Personally destroy a hostile undead, fiend, or aberration during the quest.',110),
    ('iron-vanguard','Against the Unholy','Personally destroy a hostile humanoid, undead or fiend during the quest.',120),
    ('iron-vanguard','Against the Mutant','Personally destroy a hostile humanoid, abberation or monstrosity during the quest.',130),

    ('black-hand','One Cut','Within a single turn, reduce an enemy from full HP to none.',10),
    ('black-hand','Leave No Signature','Ensure no surviving witness can identify you.',20),
    ('black-hand','The Deserving','Establish through evidence or confession that a target was guilty of a specific crime/has done harm before you kill them.',30),
    ('black-hand','A Debt Repaid','Aid someone who cannot pay you, or refuse your share of gold rewards.',40),
    ('black-hand','Cut the Root','Identify who gave the orders, not just who carried them out, by speaking to an enemy as an action during combat.',50),
    ('black-hand','No One Will Notice If There''s Nobody to Notice','Personally deliver the killing blow to at least one enemy without any other enemy witnessing it.',60),
    ('black-hand','Must Have Been the Wind','End a combat encounter having never been a target of a successful enemy attack.',70),
    ('black-hand','Clean Work','Complete the quest without leaving any collateral damage: no structures broken, no bystanders harmed, nothing burned.',80),
    ('black-hand','No Trace','Complete the quest without leaving any evidence that you were ever there.',90),
    ('black-hand','The Kindness Nobody Sees','Do something quietly good for someone during the quest without any party member(to your knowledge) noticing you do it.',100),

    ('dread-legion','Flavour Flair','Before initiative is joined on a quest, use your highest level spell slot to do anything that is not a prebuff.',10),
    ('dread-legion','Power of Darkness','Have the first spell you cast during the quest use your highest available spell slot.',20),
    ('dread-legion','Harvest the Fallen','Personally reduce at least three enemies to 0 Hit Points with necrotic, poison, cold damage or damage from summons.',30),
    ('dread-legion','Nothing Wasted','Ensure no enemy corpse is left behind: destroy, animate, or claim every body before leaving the site.',40),
    ('dread-legion','Bloom from Rot','Heal or restore a creature to life, undeath, health or freedom in a place where something died during the quest.',50),
    ('dread-legion','Names for the Ledger','Learn the true name of an enemy who dies during the quest, and speak it aloud before leaving.',60),
    ('dread-legion','Take What Endures','Recover an object from the site that predates its current occupants.',70),
    ('dread-legion','Troops for the Legion','Personally deliver the killing blow to at least one enemy during the quest.',80),
    ('dread-legion','What Was Owed','Collect something from an enemy that it took from someone else.',90),
    ('dread-legion','Speak With the Dead','Learn something from a corpse, a grave, a ghost, or a record at the quest site.',100),
    ('dread-legion','The Rites Observed','Give proper burial, prayer, or remembrance to the dead at the quest site, whoever they were and however they died.',110),
    ('dread-legion','Endings Are Not Wasted','Turn a death of someone during the quest into something the party gains from.',120),

    ('dawnwardens','Do Not Leave Them There','Find someone in genuine trouble who was not part of the objective, and help them.',10),
    ('dawnwardens','Everyone Comes Home','Ensure every party member is conscious and every rescued person alive at the quest''s end.',20),
    ('dawnwardens','The Harder Mercy','You personally must not kill anyone during the quest.',30),
    ('dawnwardens','Endure It','Deal no damage to hostile creatures during the first round of any combat with hostile enemies.',40),
    ('dawnwardens','The Rites Observed','Give proper burial, prayer, or remembrance to the dead at the quest site, whoever they were and however they died.',50),
    ('dawnwardens','Wrath of the Just','Personally deliver the killing blow to at least one enemy that harmed a civilian or non-combatant.',60),
    ('dawnwardens','Lightbringer','Bring literal or magical light into a place that has been in the dark.',70),
    ('dawnwardens','Speak the Words','Openly declare your faith, your cause, or your conviction to an enemy before fighting them.',80),
    ('dawnwardens','Against the Unclean','Personally destroy a hostile undead, fiend, or aberration during the quest.',90),
    ('dawnwardens','Against the Unholy','Personally destroy a hostile humanoid, undead or fiend during the quest.',100),
    ('dawnwardens','Against the Mutant','Personally destroy a hostile humanoid, abberation or monstrosity during the quest.',110),
    ('dawnwardens','Hold the Ground','End two consequtive turns in combat in the same location.',120),
    ('dawnwardens','Dazzling Flash of Light','Have the first spell you cast during the quest use your highest available spell slot.',130),

    ('verdant-accord','Flavour Flair','Before initiative is joined on a quest, use your highest level spell slot to do anything that is not a prebuff.',10),
    ('verdant-accord','Wild Energies','Have the first spell you cast during the quest use your highest available spell slot.',20),
    ('verdant-accord','Leave No Scar','Do not destroy or deliberately damage any natural terrain, plant life, or non-hostile creature.',30),
    ('verdant-accord','Only What Is Needed','Do not personally kill any creature that you could have bypassed, restrained, frightened off, or otherwise handled non-lethally.',40),
    ('verdant-accord','Return to the Earth','Before leaving, bury, compost, or otherwise return at least one slain creature to the natural cycle.',50),
    ('verdant-accord','Shelter the Small','Protect a non-combatant animal, plant, nest, den, grove, or similar vulnerable part of the local ecosystem from harm.',60),
    ('verdant-accord','Weather the Storm','Overcome a significant natural hazard without magically bypassing it entirely.',70),
    ('verdant-accord','Sanctuary','Establish a safe place where local wildlife or civilians can shelter from the quests threat.',80),
    ('verdant-accord','Rewild It','Leave behind something growing where nothing grew before: plant, seed or mushroom.',90),
    ('verdant-accord','The Land Provides','Sustain yourself or the party for the duration of the quest using only what the land offers.',100),

    ('dragons-den-of-drama','Bring Back the Story','Make a short song, spectacle, or poem about the quest and bring it back to the Poets Hoard.',10),
    ('dragons-den-of-drama','A Fitting Exit','End a significant encounter with a line, gesture, or flourish.',20),
    ('dragons-den-of-drama','Prepare for Action','Spend at least one full Action doing nothing, mechanically, while in an active initiative with hostile enemies.',30),
    ('dragons-den-of-drama','You Dare Touch Me?!','You cannot target any enemy who hasnt yet damaged or effected you in any way.',40),
    ('dragons-den-of-drama','Woe Is Me!','At least once during the quest, before rolling an attack, declare that it misses and describe the failure in as tragic and overwrought a manner as you can manage.',50),
    ('dragons-den-of-drama','Apparel Appeal','Describe your character wearing different clothing and/or equipment than the last time you described them.',60),
    ('dragons-den-of-drama','Slogan to Die For','Repeat a flourish, catchphrase, or gesture at least three times during the quest, in three different situations.',70),

    ('crucible-of-creation','Salvage Rights','Recover materials, components, or intact mechanisms from something broken or destroyed during the quest.',10),
    ('crucible-of-creation','Improvised Solution','Solve a problem or kill an enemy using only materials or terrain found at the quest site.',20),
    ('crucible-of-creation','Field Friend','You are given a construct prototype to test: a Small construct using a Modron Monodrone''s statistics. It follows your commands to the best of its ability. Ensure it survives until the end of the quest.',30),
    ('crucible-of-creation','Science!','You are given a Wand of Magic Missiles with seven charges. Use it to deliver the killing blow on a hostile enemy before the quest ends and report the result. The wand dissapears afterwards.',40),
    ('crucible-of-creation','Dismantle','Dismantle a structure, construction or creation during the quest using skill rather than force.',50),
    ('crucible-of-creation','I knew it would come in handy','Make use of an item you normally dont, during the quest.',60),
    ('crucible-of-creation','Deadly Contraption-thing','Reduce a significant enemy to 0 HP using the ability of an item you have equipped.',70),

    ('the-argent-mark','See It First','Personally detect the quest''s primary threat before it detects the party.',10),
    ('the-argent-mark','Never Surprised','Never be surprised or ambushed during the quest.',20),
    ('the-argent-mark','Long Shot','Reduce a significant enemy to 0 Hit Points, without it ever comes within 20 feet of you.',30),
    ('the-argent-mark','The High Ground','Hold an elevated or commanding position for the duration of an encounter.',40),
    ('the-argent-mark','Just As Planned','Successfully surprise or ambush at least one enemy during the quest.',50),
    ('the-argent-mark','Prepare for Strike','At least once during the quest, take the Ready action and take no other Action, Bonus Action, or Reaction that turn.',60),
    ('the-argent-mark','Keep Your Distance','Reduce a significant enemy to 0 hit points while more than 30ft away from it.',70),
    ('the-argent-mark','Called Shot','At least twice during the quest, declare your target at the start of your turn(no action require) and hit the target with at least one attack before the end of the current turn.',80),
    ('the-argent-mark','Marked Target','At the start of initiative, declare a target as your quarry. You cannot target other enemies with attacks while your quarry still stands.',90),

    ('the-ashen-veil','Knowledge of the Slayer','Identify a creature''s nature, type, resistances, immunities, or any notable ability before fighting it, using investigation, lore, magic, or firsthand observation of any kind.',10),
    ('the-ashen-veil','Blade of Silver','Defeat a significant enemy using a damage type, weapon, spell, item, or other method specifically chosen because of that creature''s known weakness.',20),
    ('the-ashen-veil','For a Price','Before the quest ends, speak with an NPC who has a problem with a creature and agree to resolve it.',30),
    ('the-ashen-veil','Trophy Taken','Recover a meaningful physical trophy from a defeated creature as proof of your work.',40),
    ('the-ashen-veil','Preparation for Peril','Successfully use a consumable, tool, potion, poison, oil, trap, or other consumable to counter or nullify a creature''s ability.',50),
    ('the-ashen-veil','The Lesser Evil','Choose between two morally grey (unpleasant) outcomes and deliberately accept the one that causes the lesser harm.',60),
    ('the-ashen-veil','Pay Me When It''s Done','Complete the quest without receiving payment, loot, or another promised reward until the very end.',70),
    ('the-ashen-veil','Defy Death','Defeat an opponent after it has reduced you to 0 HP.',80),
    ('the-ashen-veil','The Butcher''s Work','Reduce a significant monster from full health to 0 HP using only mundane weapons, items, or the environment.',90),
    ('the-ashen-veil','Duel the Dealer','Defeat a significant opponent in a 1 on 1 duel without outside assistance (even if they break the 1 on 1)',100),

    ('wayfarers-respite','A home to all','Establish a outpost(building one or taking a building) of the wayfarers respite.',10),
    ('wayfarers-respite','HUIAHDUIGHAUI','Challenge a significant enemy to a drinking contest(by spending an action in initiative). Then beat them in that contest(or beat them up).',20),
    ('wayfarers-respite','A drink with the lads','Succesfully avoid a encounter by befriending the enemies or talking them down.',30),
    ('wayfarers-respite','Make it fair','Use your guild benefit on a enemy then beat them in a battle.',40),
    ('wayfarers-respite','Light the way','Make one encouraging speech that rallies an npc to your cause.',50),
    ('wayfarers-respite','The bartender','Listen to someones struggles and give them good advice.',60),

    ('eclipsed-choir','Find Your Voice','Use a performance check to deescalate a situation.',10),
    ('eclipsed-choir','The First Note','Be the first creature to willingly make a sound during an encounter.',20),
    ('eclipsed-choir','Direct Dissonance','Cause an enemy to suffer a condition or otherwise become impaired within a round of another party member affecting them.',30),
    ('eclipsed-choir','Conduct the Choir','Successfully direct another creature''s action, movement, or ability in a way that directly contributes to overcoming an obstacle.',40),
    ('eclipsed-choir','Encore','Repeat the same successful action, spell, or ability against the same target on two consecutive turns.',50),
    ('eclipsed-choir','The Soloist','Successfully complete a significant part of the quest while acting entirely alone, without assistance from another party member.',60),
    ('eclipsed-choir','A Voice in the Dark','Communicate with or persuade a creature that cannot understand your language using only sound, rhythm, music, or song.',70),
    ('eclipsed-choir','They shall Sing your Name','Learn the name of a creature encountered during the quest and use it in conversation with them.',80),
    ('eclipsed-choir','Break the Rhythm','Interrupt an enemy''s ongoing action, spell, ritual, or ability.',90),
    ('eclipsed-choir','The Eclipsed Verse','Witness something beautiful, terrible, or otherwise extraordinary during the quest and preserve it through music before leaving.',100)
) AS v(guild_slug, title, description, sort_order)
  ON v.guild_slug = g.slug
ON CONFLICT (guild_id, title) DO UPDATE
SET
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  is_published = EXCLUDED.is_published,
  updated_at = NOW();
